---
title: "FRS"
author: "Bryan Kim"
date: "9/15/2020"
output: pdf_document
---

```{r}
######################################################################
#### ESTIMATING THE 10 YEAR CARDIOVASCULAR DISEASE RISK IN ADULTS ####
######################################################################

# Originating from the Framingham Risk Study, the model is based on a Cox Proportional Hazard Model

### Required packages ###
library(ggplot2); library(dplyr); library(tidyr);library(haven);library(readstata13);library(foreign)
### Parameters ###
f_base10_survival = 0.95012 # baseline 10-year survival for females
m_base10_survival = 0.88936 # baseline 10-year survival for males

f_rf <- list(log_age = 2.32888, log_totchol = 1.20904,log_hdl = -0.70833,log_SBP = 2.82263,Smoking = 0.52873,Diabetes = 0.69154) #  log of hazard ratio for each risk factor for females
m_rf <- list(log_age = 3.06117, log_totchol = 1.12370,log_hdl = -0.93263,log_SBP = 1.99881,Smoking = 0.65451,Diabetes = 0.57367) #  log of hazard ratio for each risk factor for males 
betas <- list(f=f_rf,m=m_rf) # nested list of f_rf and m_rf

f_points=data.frame("points"=seq(-3,12),"age_low"=c(NA,NA,NA,30,NA,35,NA,40,45,NA,50,55,60,65,70,75),"age_high"=c(NA,NA,NA,34,NA,39,NA,44,49,NA,54,59,64,69,74,120),"HDL_low"=c(NA,60,50,45,35,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"HDL_high"=c(NA,1000,59,49,44,35,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_low"=c(NA,NA,NA,0,160,NA,200,240,280,NA,NA,NA,NA,NA,NA,NA),"TotChol_high"=c(NA,NA,NA,160,199,NA,239,279,1000,NA,NA,NA,NA,NA,NA,NA), "SBP_low"=c(NA,NA,0,NA,NA,NA,120,130,NA,140,150,160,NA,NA,NA,NA),"SBP_high"=c(NA,NA,120,NA,NA,NA,129,139,NA,149,159,1000,NA,NA,NA,NA), "Smoker"=c(NA,NA,NA,"No",NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA), "Diabetic"=c(NA,NA,NA,"No",NA,NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA))
m_points=data.frame("points"=seq(-2,15),"age_low"=c(NA,NA,30,NA,35,NA,NA,40,45,NA,50,NA,55,60,65,NA,70,75),"age_high"=c(NA,NA,34,NA,39,NA,NA,44,49,NA,54,NA,59,64,69,NA,74,120),"HDL_low"=c(60,50,45,35,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"HDL_high"=c(1000,59,49,44,35,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_low"=c(NA,NA,0,160,200,240,280,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_high"=c(NA,NA,160,199,239,279,1000,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "SBP_low"=c(NA,NA,0,NA,120,130,140,160,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"SBP_high"=c(NA,NA,120,NA,129,139,149,1000,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "Smoker"=c(NA,NA,"No",NA,NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "Diabetic"=c(NA,NA,"No",NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA))


################################################################################################################################################################
# This gets the row where the input (30 in this example) satisfies the condition that it is between the age_low and age_high columns of the data frame f_points
i=sapply(30, function(p) { which(f_points$age_low <= p & f_points$age_high >= p)})
# Delete all rows except row "i"
keep_df=f_points[-(setdiff(1:16,i)),]
################################################################################################################################################################

test_func = function(age) {
  list_pts=c() # Initiate list of points
  i=sapply(age, function(p) { which(m_points$age_low <= p & m_points$age_high >= p)})
  return(i)
}
test_func=Vectorize(test_func)
test$test <- test_func(test$riagendr)

get_frs = function(riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic) {
  list_pts=c() # Initiate list of points
  #### MALES ####
  if (riagendr == 1) {
   ## GET POINTS FROM AGE ##
  i=sapply(ridageyr, function(p) { which(m_points$age_low <= p & m_points$age_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_age <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]]) 
  ## GET POINTS FROM HDL ##
  i=sapply(HDL, function(p) { which(m_points$HDL_low <= p & m_points$HDL_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_HDL <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM TOTAL CHOLESTEROL ##
  i=sapply(TotChol, function(p) { which(m_points$TotChol_low <= p & m_points$TotChol_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_TotChol <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SBP ##
  i=sapply(sbp, function(p) { which(m_points$SBP_low <= p & m_points$SBP_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_SBP <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SMOKER ##
  if (isTRUE(smoker == 2)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,4)}
  # m_smoke <<- 4
  ## GET POINTS FROM DIABETIC ##
  if (isTRUE(diabetic < 6.5)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,3)}
  # m_diabetic <<- 3
  }
  #### FEMALES ####
 else {
     ## GET POINTS FROM AGE ##
  i=sapply(ridageyr, function(p) { which(f_points$age_low <= p & f_points$age_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_age <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]]) 
  ## GET POINTS FROM HDL ##
  i=sapply(HDL, function(p) { which(f_points$HDL_low <= p & f_points$HDL_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_HDL <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM TOTAL CHOLESTEROL ##
  i=sapply(TotChol, function(p) { which(f_points$TotChol_low <= p & f_points$TotChol_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_TotChol <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SBP ##
  i=sapply(sbp, function(p) { which(f_points$SBP_low <= p & f_points$SBP_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_SBP <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SMOKER ##
  if (isTRUE(smoker == 2)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,3)}
  # f_smoke <<- 3
  ## GET POINTS FROM DIABETIC ##
  if (isTRUE(diabetic <  6.5)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,4)}
  # f_diabetic <<- 4
  }
  return(sum(list_pts))
}

################################################################################################################################################################
# THE AVERAGES IN THE COX MODEL DEPEND ON OUR PARTICULAR SAMPLE AND THE CHARACTERISTICS OF THAT SAMPLE.

### COX MODEL ESTIMATE ###
# FEMALES
# arg1_f = betas$f$log_age*log(age)+betas$f$log_totchol*log(TotChol)+betas$f$log_hdl*log(HDL)+betas$f$log_SBP*log(sbp)+betas$f$Smoking*smoker+betas$f$Diabetes*diabetic
# arg2_f = 0 # THE MEAN VALUES HERE #
# 
# rho_f = 1-(f_base10_survival^exp(arg1_f - arg2_f))
# # MALES
# arg1_m = betas$m$log_age*log(age)+betas$m$log_totchol*log(TotChol)+betas$m$log_hdl*log(HDL)+betas$m$log_SBP*log(sbp)+betas$m$Smoking*smoker+betas$m$Diabetes*diabetic
# arg2_m= 0  # THE MEAN VALUES HERE #
# 
# rho_m = 1-(m_base10_survival^exp(arg1_m - arg2_m))
```

```{r}
# order: riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic
##########################################
##               1999-2000              ##
##########################################
nhanes1999_2000=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_1999_2000_full.dta")
nhanes1999_2000=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_1999_2000_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes1999_2000= nhanes1999_2000[complete.cases(nhanes1999_2000[ , c("riagendr","ridageyr","lbdhdl","lbxtc","bpxsar","smoke_sts","lbxgh")]),]
nhanes1999_2000$frs = mapply(get_frs, nhanes1999_2000$riagendr,nhanes1999_2000$ridageyr,nhanes1999_2000$lbdhdl,nhanes1999_2000$lbxtc,nhanes1999_2000$bpxsar,nhanes1999_2000$smoke_sts,nhanes1999_2000$lbxgh)

write_dta(nhanes1999_2000, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_1999_2000_frs.dta")

##########################################
##               2001-20012             ##
##########################################
nhanes2001_2002=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2001_2002_full.dta")
nhanes2001_2002=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2001_2002_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2001_2002= nhanes2001_2002[complete.cases(nhanes2001_2002[ , c("riagendr","ridageyr","lbdhdl","lbxtc","bpxsar","smoke_sts","lbxgh")]),]
nhanes2001_2002$frs = mapply(get_frs, nhanes2001_2002$riagendr,nhanes2001_2002$ridageyr,nhanes2001_2002$lbdhdl,nhanes2001_2002$lbxtc,nhanes2001_2002$bpxsar,nhanes2001_2002$smoke_sts,nhanes2001_2002$lbxgh)

write_dta(nhanes2001_2002, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2001_2002_frs.dta")

##########################################
##               2003_20034             ##
##########################################
nhanes2003_2004=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2003_2004_full.dta")
nhanes2003_2004=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2003_2004_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2003_2004= nhanes2003_2004[complete.cases(nhanes2003_2004[ , c("riagendr","ridageyr","lbxhdd","lbxtc","bpxsar","smoke_sts","lbxgh")]),]
nhanes2003_2004$frs = mapply(get_frs, nhanes2003_2004$riagendr,nhanes2003_2004$ridageyr,nhanes2003_2004$lbxhdd,nhanes2003_2004$lbxtc,nhanes2003_2004$bpxsar,nhanes2003_2004$smoke_sts,nhanes2003_2004$lbxgh)

write_dta(nhanes2003_2004, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2003_2004_frs.dta")

##########################################
##               2005_2006            ##
##########################################
nhanes2005_2006=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2005_2006_full.dta")
nhanes2005_2006=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2005_2006_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2005_2006= nhanes2005_2006[complete.cases(nhanes2005_2006[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2005_2006$frs = mapply(get_frs, nhanes2005_2006$riagendr,nhanes2005_2006$ridageyr,nhanes2005_2006$lbdhdd,nhanes2005_2006$lbxtc,nhanes2005_2006$asbp,nhanes2005_2006$smoke_sts,nhanes2005_2006$lbxgh)

write_dta(nhanes2005_2006, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2005_2006_frs.dta")

##########################################
##               2007_2008          ##
##########################################
nhanes2007_2008=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2007_2008_full.dta")
nhanes2007_2008=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2007_2008_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2007_2008= nhanes2007_2008[complete.cases(nhanes2007_2008[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2007_2008$frs = mapply(get_frs, nhanes2007_2008$riagendr,nhanes2007_2008$ridageyr,nhanes2007_2008$lbdhdd,nhanes2007_2008$lbxtc,nhanes2007_2008$asbp,nhanes2007_2008$smoke_sts,nhanes2007_2008$lbxgh)

write_dta(nhanes2007_2008, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2007_2008_frs.dta")

##########################################
##               2009_2010          ##
##########################################
nhanes2009_2010=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2000_2010_full.dta")
nhanes2009_2010=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2009_2010_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2009_2010= nhanes2009_2010[complete.cases(nhanes2009_2010[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2009_2010$frs = mapply(get_frs, nhanes2009_2010$riagendr,nhanes2009_2010$ridageyr,nhanes2009_2010$lbdhdd,nhanes2009_2010$lbxtc,nhanes2009_2010$asbp,nhanes2009_2010$smoke_sts,nhanes2009_2010$lbxgh)

write_dta(nhanes2009_2010, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2009_2010_frs.dta")

##########################################
##               2009_2010          ##
##########################################
nhanes2011_2012=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2011_2012_full.dta")
nhanes2011_2012=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2011_2012_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2011_2012= nhanes2011_2012[complete.cases(nhanes2011_2012[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2011_2012$frs = mapply(get_frs, nhanes2011_2012$riagendr,nhanes2011_2012$ridageyr,nhanes2011_2012$lbdhdd,nhanes2011_2012$lbxtc,nhanes2011_2012$asbp,nhanes2011_2012$smoke_sts,nhanes2011_2012$lbxgh)

write_dta(nhanes2011_2012, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2011_2012_frs.dta")

##########################################
##               2009_2010          ##
##########################################
nhanes2013_2014=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2013_2014_full.dta")
nhanes2013_2014=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2013_2014_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2013_2014= nhanes2013_2014[complete.cases(nhanes2013_2014[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2013_2014$frs = mapply(get_frs, nhanes2013_2014$riagendr,nhanes2013_2014$ridageyr,nhanes2013_2014$lbdhdd,nhanes2013_2014$lbxtc,nhanes2013_2014$asbp,nhanes2013_2014$smoke_sts,nhanes2013_2014$lbxgh)

write_dta(nhanes2013_2014, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2013_2014_frs.dta")

##########################################
##               2009_2010          ##
##########################################
nhanes2015_2016=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2015_2016_full.dta")
nhanes2015_2016=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2015_2016_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2015_2016= nhanes2015_2016[complete.cases(nhanes2015_2016[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2015_2016$frs = mapply(get_frs, nhanes2015_2016$riagendr,nhanes2015_2016$ridageyr,nhanes2015_2016$lbdhdd,nhanes2015_2016$lbxtc,nhanes2015_2016$asbp,nhanes2015_2016$smoke_sts,nhanes2015_2016$lbxgh)

write_dta(nhanes2015_2016, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2015_2016_frs.dta")

##########################################
##               2009_2010          ##
##########################################
nhanes2017_2018=read_dta("/Users/bryankim/Documents/TEMPORARY FILES/nhanes_2017_2018_full.dta")
nhanes2017_2018=read_dta("/homes/nber/kimcwa/Documents/casedeaton/NHANES/LMF Data/NHANES continuous/nhanes_2017_2018_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanes2017_2018= nhanes2017_2018[complete.cases(nhanes2017_2018[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","smoke_sts","lbxgh")]),]
nhanes2017_2018$frs = mapply(get_frs, nhanes2017_2018$riagendr,nhanes2017_2018$ridageyr,nhanes2017_2018$lbdhdd,nhanes2017_2018$lbxtc,nhanes2017_2018$asbp,nhanes2017_2018$smoke_sts,nhanes2017_2018$lbxgh)

write_dta(nhanes2017_2018, "/homes/nber/kimcwa/Documents/casedeaton/nhanes_2017_2018_frs.dta")

##########################################
##               NHANES III          ##
##########################################
nhanesIII=read_dta("/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanesIII= nhanesIII[complete.cases(nhanesIII[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","GHP")]),]
nhanesIII$frs = mapply(get_frs, nhanesIII$HSSEX,nhanesIII$HSAGEIR,nhanesIII$HDP,nhanesIII$TCP,nhanesIII$PEPMNK1R,nhanesIII$smoke_sts,nhanesIII$GHP)
#PHASE 1
nhanesIIIP1 = filter(nhanesIII,SDPPHASE==1)
#PHASE 2
nhanesIIIP2 = filter(nhanesIII,SDPPHASE==2)
write_dta(nhanesIII, "/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_12_frs.dta")
write_dta(nhanesIIIP1, "/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_P1x_frs.dta")
write_dta(nhanesIIIP2, "/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_P2x_frs.dta")



```

```{r}
##########################################
###     Age-Sex Adjusted Calculations  ###
##########################################

# FROM DAVID:
#   Another way to do an ‘all’ calculation is to age-sex adjust. Here’s the easiest way to do that:
#   We have weights for each person, call it wi.
#   Form the age-sex group for each person (45-49M, 45-49F, 50-54M, …)
#   To age-sex adjust, let’s choose a standard year, 2009-2010.
#   Form the sum of weights for each age-sex group in 2009-10. Call that w_as_2009_10
#   Form the sum of weights for each age-sex group in each other year. Call that w_as_t.
#   Multiply each person’s weight by (w_as_2009_10/w_as_t).

## FORMING AGE-SEX GROUPS FOR EACH PERSON
# 45-54, MALES & FEMALES
#lapply(df_list, function(x) {mutate(temp, M1 = ifelse(ridageyr >= 45 & ridageyr <= 54 & riagendr == 1, 1, 0))})
temp = df_list %>% lapply(function(x) {mutate(x, M1 = ifelse(ridageyr >= 45 & ridageyr <= 54 & riagendr == 1, 1, 0))})
temp = temp %>% lapply(function(x) {mutate(x, F1 = ifelse(ridageyr >= 45 & ridageyr <= 54 & riagendr == 2, 1, 0))})
# 55-64, MALES & FEMALES
temp = temp %>% lapply(function(x) {mutate(x, M2 = ifelse(ridageyr >= 55 & ridageyr <= 64 & riagendr == 1, 1, 0))})
temp = temp %>% lapply(function(x) {mutate(x, F2 = ifelse(ridageyr >= 55 & ridageyr <= 64 & riagendr == 2, 1, 0))})
# 65-74, MALES & FEMALES
temp = temp %>% lapply(function(x) {mutate(x, M3 = ifelse(ridageyr >= 65 & ridageyr <= 74 & riagendr == 1, 1, 0))})
temp = temp %>% lapply(function(x) {mutate(x, F3 = ifelse(ridageyr >= 65 & ridageyr <= 74 & riagendr == 2, 1, 0))})
# 75+, MALES & FEMALES
temp = temp %>% lapply(function(x) {mutate(x, M4 = ifelse(ridageyr >= 75 & riagendr == 1, 1, 0))})
temp = temp %>% lapply(function(x) {mutate(x, F4 = ifelse(ridageyr >= 75 & riagendr == 2, 1, 0))})



## FOR 2009-2010, FORM SUM OF WEIGHTS FOR EACH AGE-SEX GROUP - call it w_as_2009_2010
w_M1_2009_2010 = temp[[6]] %>% filter(M1 == 1) %>% select(wtint2yr) %>% sum
w_F1_2009_2010 = temp[[6]] %>% filter(F1 == 1) %>% select(wtint2yr) %>% sum
w_M2_2009_2010 = temp[[6]] %>% filter(M2 == 1) %>% select(wtint2yr) %>% sum
w_F2_2009_2010 = temp[[6]] %>% filter(F2 == 1) %>% select(wtint2yr) %>% sum
w_M3_2009_2010 = temp[[6]] %>% filter(M3 == 1) %>% select(wtint2yr) %>% sum
w_F3_2009_2010 = temp[[6]] %>% filter(F3 == 1) %>% select(wtint2yr) %>% sum
w_M4_2009_2010 = temp[[6]] %>% filter(M4 == 1) %>% select(wtint2yr) %>% sum
w_F4_2009_2010 = temp[[6]] %>% filter(F4 == 1) %>% select(wtint2yr) %>% sum

## FORM SUM OF WEIGHT FOR EACH AGE-SEX GROUP IN EACH OTHER YEAR 
index = 1
for (year in c("1999_2000","2001_2002","2003_2004","2005_2006","2007_2008","2011_2012","2013_2014","2015_2016","2017_2018"))

  {
  for (sex in c("M","F")) {
    for (cat in c(1,2,3,4)) {
      assign(paste("w_",sex,cat,"_",year,sep = ""),temp[[index]] %>% filter(eval(parse(text = paste(sex,cat,sep=""))) == 1) %>% select(wtint2yr) %>% sum)
  }
  }
    if (index == 5) {index = 7} else {index = index + 1}
}



## MULTIPLY EACH PERSON'S WEIGHT BY (w_as_2009_10/w_as_t)


temp[[10]] = mutate(temp[[10]],wt = case_when(M1 == 1 ~ eval(wtint2yr)*(eval(w_M1_2009_2010)/(eval(w_M1_2017_2018))),
                                            F1 == 1 ~ eval(wtint2yr)*(eval(w_F1_2009_2010)/(eval(w_F1_2017_2018))),
                                            M2 == 1 ~ eval(wtint2yr)*(eval(w_M2_2009_2010)/(eval(w_M2_2017_2018))),
                                            F2 == 1 ~ eval(wtint2yr)*(eval(w_F2_2009_2010)/(eval(w_F2_2017_2018))),
                                            M3 == 1 ~ eval(wtint2yr)*(eval(w_M3_2009_2010)/(eval(w_M3_2017_2018))),
                                            F3 == 1 ~ eval(wtint2yr)*(eval(w_F3_2009_2010)/(eval(w_F3_2017_2018))),
                                            M4 == 1 ~ eval(wtint2yr)*(eval(w_M4_2009_2010)/(eval(w_M4_2017_2018))),
                                            F4 == 1 ~ eval(wtint2yr)*(eval(w_F4_2009_2010)/(eval(w_F4_2017_2018))),
                                            TRUE ~ NA_real_))

 
sum(temp[[10]][which(temp[[10]][,193]==1),195])
which(colnames(temp[[10]])=="M4")
which(colnames(temp[[10]])=="wt")


# "ALL" AGE-SEX ADJUSTED
lapply(temp, function(x) print(weighted.mean(x$frs,x$wt)))
##### BY EDUCATION #####
# <HS 
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 <= 2);print(weighted.mean(temp$frs,temp$wt))})

# HS
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 3);print(weighted.mean(temp$frs,temp$wt))})

# Some College
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 4);print(weighted.mean(temp$frs,temp$wt))})

# College Grad
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 5);print(weighted.mean(temp$frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=45 & x$ridageyr <=54);print(weighted.mean(temp$frs,temp$wt))})
# 55-64
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=55 & x$ridageyr <=64);print(weighted.mean(temp$frs,temp$wt))})
# 65-74
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=65 & x$ridageyr <=74);print(weighted.mean(temp$frs,temp$wt))})
# 75+
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=75);print(weighted.mean(temp$frs,temp$wt))})

############################################################
#FOR NHANES III
temp = nhanesIIIP1
temp = mutate(temp, M1 = ifelse(HSAGEIR >= 45 & HSAGEIR <= 54 & HSSEX == 1, 1, 0))
temp = mutate(temp, F1 = ifelse(HSAGEIR >= 45 & HSAGEIR <= 54 & HSSEX == 2, 1, 0))
temp = mutate(temp, M2 = ifelse(HSAGEIR >= 55 & HSAGEIR <= 64 & HSSEX == 1, 1, 0))
temp = mutate(temp, F2 = ifelse(HSAGEIR >= 55 & HSAGEIR <= 64 & HSSEX == 2, 1, 0))
temp = mutate(temp, M3 = ifelse(HSAGEIR >= 65 & HSAGEIR <= 74 & HSSEX == 1, 1, 0))
temp = mutate(temp, F3 = ifelse(HSAGEIR >= 65 & HSAGEIR <= 74 & HSSEX == 2, 1, 0))
temp = mutate(temp, M4 = ifelse(HSAGEIR >= 75 & HSSEX == 1, 1, 0))
temp = mutate(temp, F4 = ifelse(HSAGEIR >= 75 & HSSEX == 2, 1, 0))


w_M1_nhanesIIIP1 = temp %>% filter(M1 == 1) %>% select(WTPFHX1) %>% sum
w_F1_nhanesIIIP1= temp %>% filter(F1 == 1) %>% select(WTPFHX1) %>% sum
w_M2_nhanesIIIP1= temp %>% filter(M2 == 1) %>% select(WTPFHX1) %>% sum
w_F2_nhanesIIIP1= temp %>% filter(F2 == 1) %>% select(WTPFHX1) %>% sum
w_M3_nhanesIIIP1= temp %>% filter(M3 == 1) %>% select(WTPFHX1) %>% sum
w_F3_nhanesIIIP1= temp %>% filter(F3 == 1) %>% select(WTPFHX1) %>% sum
w_M4_nhanesIIIP1= temp %>% filter(M4 == 1) %>% select(WTPFHX1) %>% sum
w_F4_nhanesIIIP1= temp %>% filter(F4 == 1) %>% select(WTPFHX1) %>% sum



temp = mutate(temp,wt = case_when(M1 == 1 ~ eval(WTPFHX1)*(eval(w_M1_1999_2000)/(eval(w_M1_nhanesIIIP1))),
                                            F1 == 1 ~ eval(WTPFHX1)*(eval(w_F1_1999_2000)/(eval(w_F1_nhanesIIIP1))),
                                            M2 == 1 ~ eval(WTPFHX1)*(eval(w_M2_1999_2000)/(eval(w_M2_nhanesIIIP1))),
                                            F2 == 1 ~ eval(WTPFHX1)*(eval(w_F2_1999_2000)/(eval(w_F2_nhanesIIIP1))),
                                            M3 == 1 ~ eval(WTPFHX1)*(eval(w_M3_1999_2000)/(eval(w_M3_nhanesIIIP1))),
                                            F3 == 1 ~ eval(WTPFHX1)*(eval(w_F3_1999_2000)/(eval(w_F3_nhanesIIIP1))),
                                            M4 == 1 ~ eval(WTPFHX1)*(eval(w_M4_1999_2000)/(eval(w_M4_nhanesIIIP1))),
                                            F4 == 1 ~ eval(WTPFHX1)*(eval(w_F4_1999_2000)/(eval(w_F4_nhanesIIIP1))),
                                            TRUE ~ NA_real_))

# "ALL" AGE-SEX ADJUSTED
weighted.mean(temp$frs,temp$wt)
temp1=temp
#<HS
temp1 = filter(temp,HFA8R <= 11);print(weighted.mean(temp1$frs,temp1$wt))
# HS
temp1 = filter(temp,HFA8R == 12);print(weighted.mean(temp1$frs,temp1$wt))
# Some College
temp1 = filter(temp,HFA8R > 12 & HFA8R < 16);print(weighted.mean(temp1$frs,temp1$wt))
# College Grad
temp1 = filter(temp,HFA8R >= 16);print(weighted.mean(temp1$frs,temp1$wt))
##### BY AGE #####
# 45-54
temp1 = filter(temp,HSAGEIR >=45 & HSAGEIR <=54);print(weighted.mean(temp1$frs,temp1$wt))
# 55-64
temp1 = filter(temp,HSAGEIR >=55 & HSAGEIR <=64);print(weighted.mean(temp1$frs,temp1$wt))
# 65-74
temp1 = filter(temp,HSAGEIR >=65 & HSAGEIR <=74);print(weighted.mean(temp1$frs,temp1$wt))
# 75+
temp1 = filter(temp,HSAGEIR >=75);print(weighted.mean(temp1$frs,temp1$wt))
############################################################
```


```{r}
##########################################
###          Summary Statistics        ###
##########################################

filenames = list.files("/homes/nber/kimcwa/Documents/casedeaton/FRS/continuous/",pattern = "_frs.dta",full.names = TRUE)
df_list = lapply(filenames,read_dta)


# "ALL"
lapply(df_list, function(x) print(weighted.mean(x$frs,x$wtint2yr)))

##### BY EDUCATION #####
# <HS 
lapply(df_list, function(x) {temp = filter(x,x$dmdeduc2 <= 2);print(weighted.mean(temp$frs,temp$wtint2yr))})

# HS
lapply(df_list, function(x) {temp = filter(x,x$dmdeduc2 == 3);print(weighted.mean(temp$frs,temp$wtint2yr))})

# Some College
lapply(df_list, function(x) {temp = filter(x,x$dmdeduc2 == 4);print(weighted.mean(temp$frs,temp$wtint2yr))})

# College Grad
lapply(df_list, function(x) {temp = filter(x,x$dmdeduc2 == 5);print(weighted.mean(temp$frs,temp$wtint2yr))})

##### BY AGE #####
# 45-54
lapply(df_list, function(x) {temp = filter(x,x$ridageyr >=45 & x$ridageyr <=54);print(weighted.mean(temp$frs,temp$wtint2yr))})
# 55-64
lapply(df_list, function(x) {temp = filter(x,x$ridageyr >=55 & x$ridageyr <=64);print(weighted.mean(temp$frs,temp$wtint2yr))})
# 65-74
lapply(df_list, function(x) {temp = filter(x,x$ridageyr >=65 & x$ridageyr <=74);print(weighted.mean(temp$frs,temp$wtint2yr))})
# 75+
lapply(df_list, function(x) {temp = filter(x,x$ridageyr >=75);print(weighted.mean(temp$frs,temp$wtint2yr))})
# 85+
lapply(df_list, function(x) {temp = filter(x,x$ridageyr >= 85);print(weighted.mean(temp$frs,temp$wtint2yr))})


############################################################
#FOR NHANES III
nhanesIII_file = list.files("/homes/nber/kimcwa/Documents/casedeaton/FRS",pattern = "x_frs.dta",full.names = TRUE)
df_listIII = lapply(nhanesIII_file,read_dta)
length(df_listIII) # should be 2

# ALL
weighted.mean(nhanesIIIP1$frs,nhanesIIIP1$WTPFHX1)
weighted.mean(nhanesIIIP2$frs,nhanesIIIP2$WTPFHX2)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# HS
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# Some College
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# College Grad
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs,temp$WTPFHX2))})

##### BY AGE #####
# 45-54
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# 55-64
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# 65-74
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# 75+
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$frs,temp$WTPFHX1))})
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$frs,temp$WTPFHX2))})

# 85+
lapply(df_listIII, function(x) {temp = filter(x,x$HSAGEIR >= 85);print(weighted.mean(temp$frs,temp$WTPFHX6))})

############################################################
```

```{r}

```

