---
title: "FRS_local2 for NHANES II and III"
author: "Bryan Kim"
date: "11/21/2020"
output: pdf_document
---

### NHANES II ###
```{r}
# order: riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic
##########################################
##               1999-2000              ##
##########################################
nhanesII=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesII_full.dta")
nhanesII= nhanesII[complete.cases(nhanesII[ , c("SEX","AGEYR_AT_INT","lbdhdd","lbxtc","asbp","smoke_sts","fpg")]),]
nhanesII = nhanesII %>% filter(lbdhdd != 888)
# Getting cox model based risk levels
# nhanes1999_2000= nhanes1999_2000[complete.cases(nhanes1999_2000[ , c("riagendr","ridageyr","lbdhdl","lbxtc","bpxsar","isSmoker","isDiabetic")]),]
# m_age = weighted.mean(nhanes1999_2000$ridageyr,nhanes1999_2000$wtint2yr)
# m_HDL= weighted.mean(nhanes1999_2000$lbdhdl,nhanes1999_2000$wtint2yr)
# m_TotChol = weighted.mean(nhanes1999_2000$lbxtc,nhanes1999_2000$wtint2yr)
# m_sbp = weighted.mean(nhanes1999_2000$bpxsar,nhanes1999_2000$wtint2yr)
# m_smoke = weighted.mean(nhanes1999_2000$isSmoker,nhanes1999_2000$wtint2yr)
# m_diabetic = weighted.mean(nhanes1999_2000$isDiabetic,nhanes1999_2000$wtint2yr)


nhanesII$frs = mapply(get_frs, nhanesII$SEX,nhanesII$AGEYR_AT_INT,nhanesII$lbdhdd,nhanesII$lbxtc,nhanesII$asbp,nhanesII$smoke_sts,nhanesII$fpg)

#FOR NHANES III
temp = nhanesII
temp = mutate(temp, M1 = ifelse(AGEYR_AT_INT >= 45 & AGEYR_AT_INT <= 54 & SEX == 1, 1, 0))
temp = mutate(temp, F1 = ifelse(AGEYR_AT_INT >= 45 & AGEYR_AT_INT <= 54 & SEX == 2, 1, 0))
temp = mutate(temp, M2 = ifelse(AGEYR_AT_INT >= 55 & AGEYR_AT_INT <= 64 & SEX == 1, 1, 0))
temp = mutate(temp, F2 = ifelse(AGEYR_AT_INT >= 55 & AGEYR_AT_INT <= 64 & SEX == 2, 1, 0))
temp = mutate(temp, M3 = ifelse(AGEYR_AT_INT >= 65 & AGEYR_AT_INT <= 74 & SEX == 1, 1, 0))
temp = mutate(temp, F3 = ifelse(AGEYR_AT_INT >= 65 & AGEYR_AT_INT <= 74 & SEX == 2, 1, 0))
temp = mutate(temp, M4 = ifelse(AGEYR_AT_INT >= 75 & SEX == 1, 1, 0))
temp = mutate(temp, F4 = ifelse(AGEYR_AT_INT >= 75 & SEX == 2, 1, 0))


w_M1_nhanesIIP2 = temp %>% filter(M1 == 1) %>% select(exam_final_wt) %>% sum
w_F1_nhanesIIP2= temp %>% filter(F1 == 1) %>% select(exam_final_wt) %>% sum
w_M2_nhanesIIP2= temp %>% filter(M2 == 1) %>% select(exam_final_wt) %>% sum
w_F2_nhanesIIP2= temp %>% filter(F2 == 1) %>% select(exam_final_wt) %>% sum
w_M3_nhanesIIP2= temp %>% filter(M3 == 1) %>% select(exam_final_wt) %>% sum
w_F3_nhanesIIP2= temp %>% filter(F3 == 1) %>% select(exam_final_wt) %>% sum
w_M4_nhanesIIP2= temp %>% filter(M4 == 1) %>% select(exam_final_wt) %>% sum
w_F4_nhanesIIP2= temp %>% filter(F4 == 1) %>% select(exam_final_wt) %>% sum



temp = mutate(temp,wt = case_when(M1 == 1 ~ eval(exam_final_wt)*(eval(w_M1_2009_2010)/(eval(w_M1_nhanesIIP2))),
                                            F1 == 1 ~ eval(exam_final_wt)*(eval(w_F1_2009_2010)/(eval(w_F1_nhanesIIP2))),
                                            M2 == 1 ~ eval(exam_final_wt)*(eval(w_M2_2009_2010)/(eval(w_M2_nhanesIIP2))),
                                            F2 == 1 ~ eval(exam_final_wt)*(eval(w_F2_2009_2010)/(eval(w_F2_nhanesIIP2))),
                                            M3 == 1 ~ eval(exam_final_wt)*(eval(w_M3_2009_2010)/(eval(w_M3_nhanesIIP2))),
                                            F3 == 1 ~ eval(exam_final_wt)*(eval(w_F3_2009_2010)/(eval(w_F3_nhanesIIP2))),
                                            #M4 == 1 ~ eval(exam_final_wt)*(eval(w_M4_2009_2010)/(eval(w_M4_nhanesIIP2))),
                                            #F4 == 1 ~ eval(exam_final_wt)*(eval(w_F4_2009_2010)/(eval(w_F4_nhanesIIP2))),
                                            TRUE ~ NA_real_))

nhanesII = temp
```

### NHANES III ###
```{r}
##########################################
##               NHANES III          ##
##########################################
nhanesIII=read_dta("/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_full.dta")
## Dropping rows where values of our risk factor variables are NA
nhanesIII= nhanesIII[complete.cases(nhanesIII[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","GHP")]),]
nhanesIII$frs = mapply(get_frs, nhanesIII$HSSEX,nhanesIII$HSAGEIR,nhanesIII$HDP,nhanesIII$TCP,nhanesIII$PEPMNK1R,nhanesIII$smoke_sts,nhanesIII$GHP)
nhanesIII$frs_fpg = mapply(get_frs, nhanesIII$HSSEX,nhanesIII$HSAGEIR,nhanesIII$HDP,nhanesIII$TCP,nhanesIII$PEPMNK1R,nhanesIII$smoke_sts,nhanesIII$fpg)
#PHASE 1
nhanesIIIP1 = filter(nhanesIII,SDPPHASE==1)
#PHASE 2
nhanesIIIP2 = filter(nhanesIII,SDPPHASE==2)
nhanesIIIP1 = filter(nhanesIIIP1,GHP != 8888)
nhanesIIIP2 = filter(nhanesIIIP2,GHP != 8888)
write_dta(nhanesIII, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_frs.dta")
write_dta(nhanesIIIP1, "/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_P1x_frs.dta")
write_dta(nhanesIIIP2, "/homes/nber/kimcwa/Documents/casedeaton/FRS/nhanesIII_P2x_frs.dta")

# With FPG stuff:
nhanesIIIP1 = read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIIIP1_full.dta")
nhanesIIIP2 = read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIIIP2_full.dta")
nhanesIIIP1$frs = mapply(get_frs, nhanesIIIP1$HSSEX,nhanesIIIP1$HSAGEIR,nhanesIIIP1$HDP,nhanesIIIP1$TCP,nhanesIIIP1$PEPMNK1R,nhanesIIIP1$smoke_sts,nhanesIIIP1$fpg)
nhanesIIIP2$frs = mapply(get_frs, nhanesIIIP2$HSSEX,nhanesIIIP2$HSAGEIR,nhanesIIIP2$HDP,nhanesIIIP2$TCP,nhanesIIIP2$PEPMNK1R,nhanesIIIP2$smoke_sts,nhanesIIIP2$fpg)
nhanesIIIP1= nhanesIIIP1[complete.cases(nhanesIIIP1[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","fpg")]),]
nhanesIIIP2= nhanesIIIP2[complete.cases(nhanesIIIP2[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","fpg")]),]
nhanesIIIP1 = nhanesIIIP1 %>% filter(HDP != 888);nhanesIIIP1 = nhanesIIIP1 %>% filter(fpg != 88888);nhanesIIIP2 = nhanesIIIP2 %>% filter(HDP != 888);nhanesIIIP2 = nhanesIIIP2 %>% filter(fpg != 88888)
unique(nhanesIIIP1$fpg)
write_dta(nhanesIIIP1, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P1x_frs.dta")
write_dta(nhanesIIIP2, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P2x_frs.dta")


#FOR NHANES III
temp=list(nhanesIIIP1,nhanesIIIP2)
# temp = nhanesIIIP2
source("/Users/bryankim/Documents/NBER/Framingham /Code/adjust_weights_nhanesIII.R")

w_M1_nhanesIIIP1 = temp[[1]] %>% filter(M1 == 1) %>% select(WTPFHX2) %>% sum
w_F1_nhanesIIIP1= temp[[1]] %>% filter(F1 == 1) %>% select(WTPFHX2) %>% sum
w_M2_nhanesIIIP1= temp[[1]] %>% filter(M2 == 1) %>% select(WTPFHX2) %>% sum
w_F2_nhanesIIIP1= temp[[1]] %>% filter(F2 == 1) %>% select(WTPFHX2) %>% sum
w_M3_nhanesIIIP1= temp[[1]] %>% filter(M3 == 1) %>% select(WTPFHX2) %>% sum
w_F3_nhanesIIIP1= temp[[1]] %>% filter(F3 == 1) %>% select(WTPFHX2) %>% sum
w_M4_nhanesIIIP1= temp[[1]] %>% filter(M4 == 1) %>% select(WTPFHX2) %>% sum
w_F4_nhanesIIIP1= temp[[1]] %>% filter(F4 == 1) %>% select(WTPFHX2) %>% sum
w_M1_nhanesIIIP2 = temp[[2]] %>% filter(M1 == 1) %>% select(WTPFHX2) %>% sum
w_F1_nhanesIIIP2= temp[[2]] %>% filter(F1 == 1) %>% select(WTPFHX2) %>% sum
w_M2_nhanesIIIP2= temp[[2]] %>% filter(M2 == 1) %>% select(WTPFHX2) %>% sum
w_F2_nhanesIIIP2= temp[[2]] %>% filter(F2 == 1) %>% select(WTPFHX2) %>% sum
w_M3_nhanesIIIP2= temp[[2]] %>% filter(M3 == 1) %>% select(WTPFHX2) %>% sum
w_F3_nhanesIIIP2= temp[[2]] %>% filter(F3 == 1) %>% select(WTPFHX2) %>% sum
w_M4_nhanesIIIP2= temp[[2]] %>% filter(M4 == 1) %>% select(WTPFHX2) %>% sum
w_F4_nhanesIIIP2= temp[[2]] %>% filter(F4 == 1) %>% select(WTPFHX2) %>% sum


temp[[1]] = mutate(temp[[1]],wt = case_when(M1 == 1 ~ eval(WTPFHX2)*(eval(w_M1_2009_2010)/(eval(w_M1_nhanesIIIP1))),
                                            F1 == 1 ~ eval(WTPFHX2)*(eval(w_F1_2009_2010)/(eval(w_F1_nhanesIIIP1))),
                                            M2 == 1 ~ eval(WTPFHX2)*(eval(w_M2_2009_2010)/(eval(w_M2_nhanesIIIP1))),
                                            F2 == 1 ~ eval(WTPFHX2)*(eval(w_F2_2009_2010)/(eval(w_F2_nhanesIIIP1))),
                                            M3 == 1 ~ eval(WTPFHX2)*(eval(w_M3_2009_2010)/(eval(w_M3_nhanesIIIP1))),
                                            F3 == 1 ~ eval(WTPFHX2)*(eval(w_F3_2009_2010)/(eval(w_F3_nhanesIIIP1))),
                                            M4 == 1 ~ eval(WTPFHX2)*(eval(w_M4_2009_2010)/(eval(w_M4_nhanesIIIP1))),
                                            F4 == 1 ~ eval(WTPFHX2)*(eval(w_F4_2009_2010)/(eval(w_F4_nhanesIIIP1))),
                                            TRUE ~ NA_real_))
temp[[2]] = mutate(temp[[2]],wt = case_when(M1 == 1 ~ eval(WTPFHX2)*(eval(w_M1_2009_2010)/(eval(w_M1_nhanesIIIP2))),
                                            F1 == 1 ~ eval(WTPFHX2)*(eval(w_F1_2009_2010)/(eval(w_F1_nhanesIIIP2))),
                                            M2 == 1 ~ eval(WTPFHX2)*(eval(w_M2_2009_2010)/(eval(w_M2_nhanesIIIP2))),
                                            F2 == 1 ~ eval(WTPFHX2)*(eval(w_F2_2009_2010)/(eval(w_F2_nhanesIIIP2))),
                                            M3 == 1 ~ eval(WTPFHX2)*(eval(w_M3_2009_2010)/(eval(w_M3_nhanesIIIP2))),
                                            F3 == 1 ~ eval(WTPFHX2)*(eval(w_F3_2009_2010)/(eval(w_F3_nhanesIIIP2))),
                                            M4 == 1 ~ eval(WTPFHX2)*(eval(w_M4_2009_2010)/(eval(w_M4_nhanesIIIP2))),
                                            F4 == 1 ~ eval(WTPFHX2)*(eval(w_F4_2009_2010)/(eval(w_F4_nhanesIIIP2))),
                                            TRUE ~ NA_real_))

nhanesIIIP1=temp[[1]]
nhanesIIIP2=temp[[2]]

```


