---
title: "FRS_bryan"
author: "Bryan Kim"
date: "10/28/2020"
output: pdf_document
---


```{r}
######################################################################
#### ESTIMATING THE 10 YEAR CARDIOVASCULAR DISEASE RISK IN ADULTS ####
######################################################################

# Originating from the Framingham Risk Study, the model is based on a Cox Proportional Hazard Model

### Required packages ###
library(ggplot2); library(dplyr); library(tidyr);library(haven);library(readstata13);library(foreign)
### Parameters ###
f_base10 = 0.95012 # baseline 10-year survival for females
m_base10 = 0.88936 # baseline 10-year survival for males

f_rf <- list(log_age = 2.32888, log_hdl = -0.70833,log_totchol = 1.20904,log_SBP = 2.82263,Smoking = 0.52873,Diabetes = 0.69154) #  log of hazard ratio for each risk factor for females
m_rf <- list(log_age = 3.06117, log_hdl = -0.93263,log_totchol = 1.12370,log_SBP = 1.99881,Smoking = 0.65451,Diabetes = 0.57367) #  log of hazard ratio for each risk factor for males 
m_log_age = 3.06117; m_log_hdl = -0.93263;m_log_totchol = 1.12370;m_log_SBP = 1.99881;m_Smoking = 0.65451;m_Diabetes = 0.57367 #  log of hazard ratio for each risk factor for males 
f_log_age = 2.32888; f_log_hdl = -0.70833;f_log_totchol = 1.20904;f_log_SBP = 2.82263;f_Smoking = 0.52873;f_Diabetes = 0.69154 #  log of hazard ratio for each risk factor for females

betas <- list(f=f_rf,m=m_rf) # nested list of f_rf and m_rf

f_points=data.frame("points"=seq(-3,12),"age_low"=c(NA,NA,NA,30,NA,35,NA,40,45,NA,50,55,60,65,70,75),"age_high"=c(NA,NA,NA,34,NA,39,NA,44,49,NA,54,59,64,69,74,120),"HDL_low"=c(NA,60,50,45,35,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"HDL_high"=c(NA,1000,59,49,44,35,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_low"=c(NA,NA,NA,0,160,NA,200,240,280,NA,NA,NA,NA,NA,NA,NA),"TotChol_high"=c(NA,NA,NA,160,199,NA,239,279,1000,NA,NA,NA,NA,NA,NA,NA), "SBP_low"=c(NA,NA,0,NA,NA,NA,120,130,NA,140,150,160,NA,NA,NA,NA),"SBP_high"=c(NA,NA,120,NA,NA,NA,129,139,NA,149,159,1000,NA,NA,NA,NA), "Smoker"=c(NA,NA,NA,"No",NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA), "Diabetic"=c(NA,NA,NA,"No",NA,NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA))
m_points=data.frame("points"=seq(-2,15),"age_low"=c(NA,NA,30,NA,35,NA,NA,40,45,NA,50,NA,55,60,65,NA,70,75),"age_high"=c(NA,NA,34,NA,39,NA,NA,44,49,NA,54,NA,59,64,69,NA,74,120),"HDL_low"=c(60,50,45,35,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"HDL_high"=c(1000,59,49,44,35,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_low"=c(NA,NA,0,160,200,240,280,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"TotChol_high"=c(NA,NA,160,199,239,279,1000,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "SBP_low"=c(NA,NA,0,NA,120,130,140,160,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA),"SBP_high"=c(NA,NA,120,NA,129,139,149,1000,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "Smoker"=c(NA,NA,"No",NA,NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA), "Diabetic"=c(NA,NA,"No",NA,NA,"Yes",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA))


################################################################################################################################################################
# This gets the row where the input (30 in this example) satisfies the condition that it is between the age_low and age_high columns of the data frame f_points
i=sapply(30, function(p) { which(f_points$age_low <= p & f_points$age_high >= p)})
# Delete all rows except row "i"
keep_df=f_points[-(setdiff(1:16,i)),]
################################################################################################################################################################

get_frs = function(riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic) {
  list_pts=c() # Initiate list of points
  #### MALES ####
  if (riagendr == 1) {
   ## GET POINTS FROM AGE ##
  i=sapply(ridageyr, function(p) { which(m_points$age_low <= p & m_points$age_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_age <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]]) 
  ## GET POINTS FROM HDL ##
  i=sapply(HDL, function(p) { which(m_points$HDL_low <= p & m_points$HDL_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_HDL <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM TOTAL CHOLESTEROL ##
  i=sapply(TotChol, function(p) { which(m_points$TotChol_low <= p & m_points$TotChol_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_TotChol <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SBP ##
  i=sapply(sbp, function(p) { which(m_points$SBP_low <= p & m_points$SBP_high >= p)}); keep_df=m_points[-(setdiff(1:length(m_points$points),i)),];m_SBP <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SMOKER ##
  if (isTRUE(smoker == 2)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,4)}
  # m_smoke <<- 4
  ## GET POINTS FROM DIABETIC ##
  if (isTRUE(diabetic < 6.5)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,3)}
  # m_diabetic <<- 3
  }
  #### FEMALES ####
 else {
     ## GET POINTS FROM AGE ##
  i=sapply(ridageyr, function(p) { which(f_points$age_low <= p & f_points$age_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_age <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]]) 
  ## GET POINTS FROM HDL ##
  i=sapply(HDL, function(p) { which(f_points$HDL_low <= p & f_points$HDL_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_HDL <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM TOTAL CHOLESTEROL ##
  i=sapply(TotChol, function(p) { which(f_points$TotChol_low <= p & f_points$TotChol_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_TotChol <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SBP ##
  i=sapply(sbp, function(p) { which(f_points$SBP_low <= p & f_points$SBP_high >= p)}); keep_df=f_points[-(setdiff(1:length(f_points$points),i)),];f_SBP <<- keep_df[[1]]
  list_pts=append(list_pts,keep_df[[1]])
  ## GET POINTS FROM SMOKER ##
  if (isTRUE(smoker == 2)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,3)}
  # f_smoke <<- 3
  ## GET POINTS FROM DIABETIC ##
  if (isTRUE(diabetic <  6.5)) {list_pts=append(list_pts,0)} else {list_pts=append(list_pts,4)}
  # f_diabetic <<- 4
  }
  return(sum(list_pts))
}

########################################################################################################

get_cox_frs = function(riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic,wt) {
  risk <<- 0
  #### MALES ####
  if (riagendr == 1) {
   arg1 <<- sum((m_log_age*log(ridageyr)),(m_log_hdl*log(HDL)),(m_log_totchol*log(TotChol)),(m_log_SBP*log(sbp)),(m_Smoking*smoker),(m_Diabetes*diabetic))
   #m_age <<- weighted.mean(ridageyr,wt);m_HDL=weighted.mean(HDL,wt);m_TotChol=weighted.mean(TotChol,wt);m_sbp=weighted.mean(sbp,wt);m_smoke=weighted.mean(smoker,wt);m_diabetic=weighted.mean(diabetic,wt)
    arg2 <<- sum((m_rf[[1]]*log(m_age)),(m_rf[[2]]*log(m_HDL)),(m_rf[[3]]*log(m_TotChol)),(m_rf[[4]]*log(m_sbp)),(m_rf[[5]]*m_smoke),(m_rf[[6]]*m_diabetic))
    risk <<- 1 - (m_base10^(exp(arg1-arg2)))
  }
  #### FEMALES ####
 else {
     arg1 <<- sum((f_log_age*log(ridageyr)),(f_log_hdl*log(HDL)),(f_log_totchol*log(TotChol)),(f_log_SBP*log(sbp)),(f_Smoking*smoker),(f_Diabetes*diabetic))
   #m_age <<- weighted.mean(ridageyr,wt);m_HDL=weighted.mean(HDL,wt);m_TotChol=weighted.mean(TotChol,wt);m_sbp=weighted.mean(sbp,wt);m_smoke=weighted.mean(smoker,wt);m_diabetic=weighted.mean(diabetic,wt)
    arg2 <<- sum((f_rf[[1]]*log(m_age)),(f_rf[[2]]*log(m_HDL)),(f_rf[[3]]*log(m_TotChol)),(f_rf[[4]]*log(m_sbp)),(f_rf[[5]]*m_smoke),(f_rf[[6]]*m_diabetic))
    risk <<- 1 - (f_base10^(exp(arg1-arg2)))
  }
  return(risk)
}

########################################################################################################

################################################################################################################################################################
# THE AVERAGES IN THE COX MODEL DEPEND ON OUR PARTICULAR SAMPLE AND THE CHARACTERISTICS OF THAT SAMPLE.

### COX MODEL ESTIMATE ###
# FEMALES
# arg1_f = betas$f$log_age*log(age)+betas$f$log_totchol*log(TotChol)+betas$f$log_hdl*log(HDL)+betas$f$log_SBP*log(sbp)+betas$f$Smoking*smoker+betas$f$Diabetes*diabetic
# arg2_f = 0 # THE MEAN VALUES HERE #
# 
# rho_f = 1-(f_base10_survival^exp(arg1_f - arg2_f))
# # MALES
# arg1_m = betas$m$log_age*log(age)+betas$m$log_totchol*log(TotChol)+betas$m$log_hdl*log(HDL)+betas$m$log_SBP*log(sbp)+betas$m$Smoking*smoker+betas$m$Diabetes*diabetic
# arg2_m= 0  # THE MEAN VALUES HERE #
# 
# rho_m = 1-(m_base10_survival^exp(arg1_m - arg2_m))
```

```{r}
# order: riagendr,ridageyr,HDL,TotChol,sbp,smoker,diabetic
##########################################
##               1999-2000              ##
##########################################
nhanes1999_2000=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_1999_2000_frs.dta")
# Getting cox model based risk levels
nhanes1999_2000= nhanes1999_2000[complete.cases(nhanes1999_2000[ , c("riagendr","ridageyr","lbdhdl","lbxtc","bpxsar","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes1999_2000$ridageyr,nhanes1999_2000$wtint2yr)
m_HDL= weighted.mean(nhanes1999_2000$lbdhdl,nhanes1999_2000$wtint2yr)
m_TotChol = weighted.mean(nhanes1999_2000$lbxtc,nhanes1999_2000$wtint2yr)
m_sbp = weighted.mean(nhanes1999_2000$bpxsar,nhanes1999_2000$wtint2yr)
m_smoke = weighted.mean(nhanes1999_2000$isSmoker,nhanes1999_2000$wtint2yr)
m_diabetic = weighted.mean(nhanes1999_2000$isDiabetic,nhanes1999_2000$wtint2yr)

nhanes1999_2000$cox_frs = mapply(get_cox_frs, nhanes1999_2000$riagendr,nhanes1999_2000$ridageyr,nhanes1999_2000$lbdhdl,nhanes1999_2000$lbxtc,nhanes1999_2000$bpxsar,nhanes1999_2000$isSmoker,nhanes1999_2000$isDiabetic,nhanes1999_2000$wtint2yr)

write_dta(nhanes1999_2000, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_1999_2000_frs.dta")

##########################################
##               2001-2002             ##
##########################################


nhanes2001_2002=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2001_2002_frs.dta")
# Getting cox model based risk levels
nhanes2001_2002= nhanes2001_2002[complete.cases(nhanes2001_2002[ , c("riagendr","ridageyr","lbdhdl","lbxtc","bpxsar","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2001_2002$ridageyr,nhanes2001_2002$wtint2yr)
m_HDL= weighted.mean(nhanes2001_2002$lbdhdl,nhanes2001_2002$wtint2yr)
m_TotChol = weighted.mean(nhanes2001_2002$lbxtc,nhanes2001_2002$wtint2yr)
m_sbp = weighted.mean(nhanes2001_2002$bpxsar,nhanes2001_2002$wtint2yr)
m_smoke = weighted.mean(nhanes2001_2002$isSmoker,nhanes2001_2002$wtint2yr)
m_diabetic = weighted.mean(nhanes2001_2002$isDiabetic,nhanes2001_2002$wtint2yr)

nhanes2001_2002$cox_frs = mapply(get_cox_frs, nhanes2001_2002$riagendr,nhanes2001_2002$ridageyr,nhanes2001_2002$lbdhdl,nhanes2001_2002$lbxtc,nhanes2001_2002$bpxsar,nhanes2001_2002$isSmoker,nhanes2001_2002$isDiabetic,nhanes2001_2002$wtint2yr)

write_dta(nhanes2001_2002, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2001_2002_frs.dta")

##########################################
##               2003_2004             ##
##########################################


nhanes2003_2004=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2003_2004_frs.dta")
# Getting cox model based risk levels
nhanes2003_2004= nhanes2003_2004[complete.cases(nhanes2003_2004[ , c("riagendr","ridageyr","lbxhdd","lbxtc","bpxsar","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2003_2004$ridageyr,nhanes2003_2004$wtint2yr)
m_HDL= weighted.mean(nhanes2003_2004$lbxhdd,nhanes2003_2004$wtint2yr)
m_TotChol = weighted.mean(nhanes2003_2004$lbxtc,nhanes2003_2004$wtint2yr)
m_sbp = weighted.mean(nhanes2003_2004$bpxsar,nhanes2003_2004$wtint2yr)
m_smoke = weighted.mean(nhanes2003_2004$isSmoker,nhanes2003_2004$wtint2yr)
m_diabetic = weighted.mean(nhanes2003_2004$isDiabetic,nhanes2003_2004$wtint2yr)

nhanes2003_2004$cox_frs = mapply(get_cox_frs, nhanes2003_2004$riagendr,nhanes2003_2004$ridageyr,nhanes2003_2004$lbxhdd,nhanes2003_2004$lbxtc,nhanes2003_2004$bpxsar,nhanes2003_2004$isSmoker,nhanes2003_2004$isDiabetic,nhanes2003_2004$wtint2yr)

write_dta(nhanes2003_2004, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2003_2004_frs.dta")

##########################################
##               2005_2006            ##
##########################################


nhanes2005_2006=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2005_2006_frs.dta")
# Getting cox model based risk levels
nhanes2005_2006= nhanes2005_2006[complete.cases(nhanes2005_2006[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2005_2006$ridageyr,nhanes2005_2006$wtint2yr)
m_HDL= weighted.mean(nhanes2005_2006$lbdhdd,nhanes2005_2006$wtint2yr)
m_TotChol = weighted.mean(nhanes2005_2006$lbxtc,nhanes2005_2006$wtint2yr)
m_sbp = weighted.mean(nhanes2005_2006$asbp,nhanes2005_2006$wtint2yr)
m_smoke = weighted.mean(nhanes2005_2006$isSmoker,nhanes2005_2006$wtint2yr)
m_diabetic = weighted.mean(nhanes2005_2006$isDiabetic,nhanes2005_2006$wtint2yr)

nhanes2005_2006$cox_frs = mapply(get_cox_frs, nhanes2005_2006$riagendr,nhanes2005_2006$ridageyr,nhanes2005_2006$lbdhdd,nhanes2005_2006$lbxtc,nhanes2005_2006$asbp,nhanes2005_2006$isSmoker,nhanes2005_2006$isDiabetic,nhanes2005_2006$wtint2yr)

write_dta(nhanes2005_2006, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2005_2006_frs.dta")

##########################################
##               2007_2008          ##
##########################################

nhanes2007_2008=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2007_2008_frs.dta")
# Getting cox model based risk levels
nhanes2007_2008= nhanes2007_2008[complete.cases(nhanes2007_2008[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2007_2008$ridageyr,nhanes2007_2008$wtint2yr)
m_HDL= weighted.mean(nhanes2007_2008$lbdhdd,nhanes2007_2008$wtint2yr)
m_TotChol = weighted.mean(nhanes2007_2008$lbxtc,nhanes2007_2008$wtint2yr)
m_sbp = weighted.mean(nhanes2007_2008$asbp,nhanes2007_2008$wtint2yr)
m_smoke = weighted.mean(nhanes2007_2008$isSmoker,nhanes2007_2008$wtint2yr)
m_diabetic = weighted.mean(nhanes2007_2008$isDiabetic,nhanes2007_2008$wtint2yr)

nhanes2007_2008$cox_frs = mapply(get_cox_frs, nhanes2007_2008$riagendr,nhanes2007_2008$ridageyr,nhanes2007_2008$lbdhdd,nhanes2007_2008$lbxtc,nhanes2007_2008$asbp,nhanes2007_2008$isSmoker,nhanes2007_2008$isDiabetic,nhanes2007_2008$wtint2yr)

write_dta(nhanes2007_2008, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2007_2008_frs.dta")

##########################################
##               2009_2010          ##
##########################################


nhanes2009_2010=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2009_2010_frs.dta")
# Getting cox model based risk levels
nhanes2009_2010= nhanes2009_2010[complete.cases(nhanes2009_2010[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2009_2010$ridageyr,nhanes2009_2010$wtint2yr)
m_HDL= weighted.mean(nhanes2009_2010$lbdhdd,nhanes2009_2010$wtint2yr)
m_TotChol = weighted.mean(nhanes2009_2010$lbxtc,nhanes2009_2010$wtint2yr)
m_sbp = weighted.mean(nhanes2009_2010$asbp,nhanes2009_2010$wtint2yr)
m_smoke = weighted.mean(nhanes2009_2010$isSmoker,nhanes2009_2010$wtint2yr)
m_diabetic = weighted.mean(nhanes2009_2010$isDiabetic,nhanes2009_2010$wtint2yr)

nhanes2009_2010$cox_frs = mapply(get_cox_frs, nhanes2009_2010$riagendr,nhanes2009_2010$ridageyr,nhanes2009_2010$lbdhdd,nhanes2009_2010$lbxtc,nhanes2009_2010$asbp,nhanes2009_2010$isSmoker,nhanes2009_2010$isDiabetic,nhanes2009_2010$wtint2yr)

write_dta(nhanes2009_2010, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2009_2010_frs.dta")

##########################################
##               2009_2010          ##
##########################################

nhanes2011_2012=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2011_2012_frs.dta")
# Getting cox model based risk levels
nhanes2011_2012= nhanes2011_2012[complete.cases(nhanes2011_2012[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2011_2012$ridageyr,nhanes2011_2012$wtint2yr)
m_HDL= weighted.mean(nhanes2011_2012$lbdhdd,nhanes2011_2012$wtint2yr)
m_TotChol = weighted.mean(nhanes2011_2012$lbxtc,nhanes2011_2012$wtint2yr)
m_sbp = weighted.mean(nhanes2011_2012$asbp,nhanes2011_2012$wtint2yr)
m_smoke = weighted.mean(nhanes2011_2012$isSmoker,nhanes2011_2012$wtint2yr)
m_diabetic = weighted.mean(nhanes2011_2012$isDiabetic,nhanes2011_2012$wtint2yr)

nhanes2011_2012$cox_frs = mapply(get_cox_frs, nhanes2011_2012$riagendr,nhanes2011_2012$ridageyr,nhanes2011_2012$lbdhdd,nhanes2011_2012$lbxtc,nhanes2011_2012$asbp,nhanes2011_2012$isSmoker,nhanes2011_2012$isDiabetic,nhanes2011_2012$wtint2yr)

write_dta(nhanes2011_2012, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2011_2012_frs.dta")

##########################################
##               2009_2010          ##
##########################################

nhanes2013_2014=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2013_2014_frs.dta")
# Getting cox model based risk levels
nhanes2013_2014= nhanes2013_2014[complete.cases(nhanes2013_2014[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2013_2014$ridageyr,nhanes2013_2014$wtint2yr)
m_HDL= weighted.mean(nhanes2013_2014$lbdhdd,nhanes2013_2014$wtint2yr)
m_TotChol = weighted.mean(nhanes2013_2014$lbxtc,nhanes2013_2014$wtint2yr)
m_sbp = weighted.mean(nhanes2013_2014$asbp,nhanes2013_2014$wtint2yr)
m_smoke = weighted.mean(nhanes2013_2014$isSmoker,nhanes2013_2014$wtint2yr)
m_diabetic = weighted.mean(nhanes2013_2014$isDiabetic,nhanes2013_2014$wtint2yr)

nhanes2013_2014$cox_frs = mapply(get_cox_frs, nhanes2013_2014$riagendr,nhanes2013_2014$ridageyr,nhanes2013_2014$lbdhdd,nhanes2013_2014$lbxtc,nhanes2013_2014$asbp,nhanes2013_2014$isSmoker,nhanes2013_2014$isDiabetic,nhanes2013_2014$wtint2yr)

write_dta(nhanes2013_2014, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2013_2014_frs.dta")

##########################################
##               2009_2010          ##
##########################################

nhanes2015_2016=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2015_2016_frs.dta")
# Getting cox model based risk levels
nhanes2015_2016= nhanes2015_2016[complete.cases(nhanes2015_2016[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2015_2016$ridageyr,nhanes2015_2016$wtint2yr)
m_HDL= weighted.mean(nhanes2015_2016$lbdhdd,nhanes2015_2016$wtint2yr)
m_TotChol = weighted.mean(nhanes2015_2016$lbxtc,nhanes2015_2016$wtint2yr)
m_sbp = weighted.mean(nhanes2015_2016$asbp,nhanes2015_2016$wtint2yr)
m_smoke = weighted.mean(nhanes2015_2016$isSmoker,nhanes2015_2016$wtint2yr)
m_diabetic = weighted.mean(nhanes2015_2016$isDiabetic,nhanes2015_2016$wtint2yr)

nhanes2015_2016$cox_frs = mapply(get_cox_frs, nhanes2015_2016$riagendr,nhanes2015_2016$ridageyr,nhanes2015_2016$lbdhdd,nhanes2015_2016$lbxtc,nhanes2015_2016$asbp,nhanes2015_2016$isSmoker,nhanes2015_2016$isDiabetic,nhanes2015_2016$wtint2yr)

write_dta(nhanes2015_2016, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2015_2016_frs.dta")

##########################################
##               2009_2010          ##
##########################################

nhanes2017_2018=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2017_2018_frs.dta")
# Getting cox model based risk levels
nhanes2017_2018= nhanes2017_2018[complete.cases(nhanes2017_2018[ , c("riagendr","ridageyr","lbdhdd","lbxtc","asbp","isSmoker","isDiabetic")]),]
m_age = weighted.mean(nhanes2017_2018$ridageyr,nhanes2017_2018$wtint2yr)
m_HDL= weighted.mean(nhanes2017_2018$lbdhdd,nhanes2017_2018$wtint2yr)
m_TotChol = weighted.mean(nhanes2017_2018$lbxtc,nhanes2017_2018$wtint2yr)
m_sbp = weighted.mean(nhanes2017_2018$asbp,nhanes2017_2018$wtint2yr)
m_smoke = weighted.mean(nhanes2017_2018$isSmoker,nhanes2017_2018$wtint2yr)
m_diabetic = weighted.mean(nhanes2017_2018$isDiabetic,nhanes2017_2018$wtint2yr)

nhanes2017_2018$cox_frs = mapply(get_cox_frs, nhanes2017_2018$riagendr,nhanes2017_2018$ridageyr,nhanes2017_2018$lbdhdd,nhanes2017_2018$lbxtc,nhanes2017_2018$asbp,nhanes2017_2018$isSmoker,nhanes2017_2018$isDiabetic,nhanes2017_2018$wtint2yr)

write_dta(nhanes2017_2018, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanes_2017_2018_frs.dta")

##########################################
##               NHANES III          ##
##########################################
nhanesIII=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_frs.dta")

nhanesIIIP1=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P1x_frs.dta")
nhanesIIIP2=read_dta("/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P2x_frs.dta")

## Dropping rows where values of our risk factor variables are NA
nhanesIII= nhanesIII[complete.cases(nhanesIII[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","isDiabetic")]),]
nhanesIIIP1= nhanesIIIP1[complete.cases(nhanesIIIP1[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","isDiabetic")]),]
nhanesIIIP2= nhanesIIIP2[complete.cases(nhanesIIIP2[ , c("HSSEX","HSAGEIR","HDP","TCP","PEPMNK1R","smoke_sts","isDiabetic")]),]

## GETTING COX FRS SCORES!!
nhanesIII$cox_frs = mapply(get_cox_frs, nhanesIII$HSSEX,nhanesIII$HSAGEIR,nhanesIII$HDP,nhanesIII$TCP,nhanesIII$PEPMNK1R,nhanesIII$isSmoker,nhanesIII$isDiabetic,nhanesIII$WTPFHX1)
nhanesIIIP1$cox_frs = mapply(get_cox_frs, nhanesIIIP1$HSSEX,nhanesIIIP1$HSAGEIR,nhanesIIIP1$HDP,nhanesIIIP1$TCP,nhanesIIIP1$PEPMNK1R,nhanesIIIP1$isSmoker,nhanesIIIP1$isDiabetic,nhanesIIIP1$WTPFHX1)
nhanesIIIP2$cox_frs = mapply(get_cox_frs, nhanesIIIP2$HSSEX,nhanesIIIP2$HSAGEIR,nhanesIIIP2$HDP,nhanesIIIP2$TCP,nhanesIIIP2$PEPMNK1R,nhanesIIIP2$isSmoker,nhanesIIIP2$isDiabetic,nhanesIIIP2$WTPFHX1)

# THIS WAS PREVIOUSLY A PROBLEM - INFLATED THE GLYCOHEMOGLOBIN NUMBERS
# nhanesIIIP1 = filter(nhanesIIIP1,GHP != 8888)
# nhanesIIIP2 = filter(nhanesIIIP2,GHP != 8888)
write_dta(nhanesIIIP1, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_frs.dta")
write_dta(nhanesIIIP1, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P1x_frs.dta")
write_dta(nhanesIIIP2, "/Users/bryankim/Documents/NBER/Framingham /Data/nhanesIII_P2x_frs.dta")


```

```{r}
## GET AGE-SEX ADJUSTED WEIGHTS



```


```{r}

######################
## RISK FACTOR TABS ##
######################
filenames = list.files("/Users/bryankim/Documents/NBER/Framingham /Data",pattern = "_frs.dta",full.names = TRUE)
filenames = filenames[-c(11,12,13)]
df_list = lapply(filenames,read_dta)

temp=list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

############################################################
 # CONTINUOUS
############################################################
temp[[1]]$HDL = temp[[1]]$lbdhdl
temp[[2]]$HDL = temp[[2]]$lbdhdl
temp[[3]]$HDL = temp[[3]]$lbxhdd
temp[[4]]$HDL = temp[[4]]$lbdhdd
temp[[5]]$HDL = temp[[5]]$lbdhdd
temp[[6]]$HDL = temp[[6]]$lbdhdd
temp[[7]]$HDL = temp[[7]]$lbdhdd
temp[[8]]$HDL = temp[[8]]$lbdhdd
temp[[9]]$HDL = temp[[9]]$lbdhdd
temp[[10]]$HDL = temp[[10]]$lbdhdd

temp[[1]]$asbp = temp[[1]]$bpxsar
temp[[2]]$asbp = temp[[2]]$bpxsar
temp[[3]]$asbp = temp[[3]]$bpxsar

temp=list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

# ALL
lapply(temp, function(x) {print(weighted.mean(x$riagendr,x$wt))})
lapply(temp, function(x) {print(weighted.mean(x$ridageyr,x$wt))})
lapply(temp, function(x) {print(weighted.mean(x$HDL,x$wt))})
lapply(temp, function(x) {print(weighted.mean(x$lbxtc,x$wt))})
lapply(temp, function(x) {print(weighted.mean(x$asbp,x$wt))})
lapply(temp, function(x) {x$isSmoker = ifelse(x$smoke_sts==1,1,0);print(weighted.mean(x$isSmoker,x$wt))})
lapply(temp, function(x) {x$isDiabetic = ifelse(x$lbxgh < 6.5,0,1);print(weighted.mean(x$isDiabetic,x$wt))})

# BY EDUCATION
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);print(weighted.mean(x$riagendr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);print(weighted.mean(x$ridageyr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);print(weighted.mean(x$HDL,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);print(weighted.mean(x$lbxtc,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);print(weighted.mean(x$asbp,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);x$isSmoker = ifelse(x$smoke_sts==1,1,0);print(weighted.mean(x$isSmoker,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 2);x$isDiabetic = ifelse(x$lbxgh < 6.5,0,1);print(weighted.mean(x$isDiabetic,x$wt))})

lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);print(weighted.mean(x$riagendr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);print(weighted.mean(x$ridageyr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);print(weighted.mean(x$HDL,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);print(weighted.mean(x$lbxtc,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);print(weighted.mean(x$asbp,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);x$isSmoker = ifelse(x$smoke_sts==1,1,0);print(weighted.mean(x$isSmoker,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 3);x$isDiabetic = ifelse(x$lbxgh < 6.3,0,1);print(weighted.mean(x$isDiabetic,x$wt))})

lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);print(weighted.mean(x$riagendr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);print(weighted.mean(x$ridageyr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);print(weighted.mean(x$HDL,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);print(weighted.mean(x$lbxtc,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);print(weighted.mean(x$asbp,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);x$isSmoker = ifelse(x$smoke_sts==1,1,0);print(weighted.mean(x$isSmoker,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 4);x$isDiabetic = ifelse(x$lbxgh < 6.4,0,1);print(weighted.mean(x$isDiabetic,x$wt))})

lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);print(weighted.mean(x$riagendr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);print(weighted.mean(x$ridageyr,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);print(weighted.mean(x$HDL,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);print(weighted.mean(x$lbxtc,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);print(weighted.mean(x$asbp,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);x$isSmoker = ifelse(x$smoke_sts==1,1,0);print(weighted.mean(x$isSmoker,x$wt))})
lapply(temp, function(x) {x=filter(x,dmdeduc2 == 5);x$isDiabetic = ifelse(x$lbxgh < 6.5,0,1);print(weighted.mean(x$isDiabetic,x$wt))})

```

```{r}
##########################################
###          Summary Statistics        ###
##########################################

# "ALL"
lapply(temp, function(x) print(weighted.mean(x$cox_frs,x$wt)))

##### BY EDUCATION #####
# <HS 
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 <= 2);print(weighted.mean(temp$cox_frs,temp$wtint2yr))})

# HS
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 3);print(weighted.mean(temp$cox_frs,temp$wt))})

# Some College
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 4);print(weighted.mean(temp$cox_frs,temp$wt))})

# College Grad
lapply(temp, function(x) {temp = filter(x,x$dmdeduc2 == 5);print(weighted.mean(temp$cox_frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=45 & x$ridageyr <=54);print(weighted.mean(temp$cox_frs,temp$wt))})
# 55-64
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=55 & x$ridageyr <=64);print(weighted.mean(temp$cox_frs,temp$wt))})
# 65-74
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=65 & x$ridageyr <=74);print(weighted.mean(temp$cox_frs,temp$wt))})
# 75+
lapply(temp, function(x) {temp = filter(x,x$ridageyr >=75);print(weighted.mean(temp$cox_frs,temp$wt))})
# 85+
lapply(temp, function(x) {temp = filter(x,x$ridageyr >= 85);print(weighted.mean(temp$cox_frs,temp$wtint2yr))})


############################################################
#FOR NHANES III
nhanesIII_file = list.files("/homes/nber/kimcwa/Documents/casedeaton/cox_frs",pattern = "x_cox_frs.dta",full.names = TRUE)
tempIII = lapply(nhanesIII_file,read_dta)
length(tempIII) # should be 2

# ALL
weighted.mean(nhanesIIIP1$cox_frs,nhanesIIIP1$wt)
weighted.mean(nhanesIIIP2$cox_frs,nhanesIIIP2$wt)

tempIII = list(nhanesIIIP1,nhanesIIIP2)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$cox_frs,temp$wt))})

# HS
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$cox_frs,temp$wt))})

# Some College
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$cox_frs,temp$wt))})

# College Grad
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$cox_frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$cox_frs,temp$wt))})

# 55-64
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$cox_frs,temp$wt))})

# 65-74
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$cox_frs,temp$wt))})

# 75+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$cox_frs,temp$wt))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$cox_frs,temp$wt))})

# 85+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >= 85);print(weighted.mean(temp$cox_frs,temp$WTPFHX6))})

############################################################
```


```{r}
## PLOTS

df_plot = data.frame("survey"=c("nhanesIIIP1","nhanesIIIP2", "nhanes1999_2000", "nhanes2001_2002","nhanes2003_2004","nhanes2005_2006","nhanes2007_2008","nhanes2009_2010" ,"nhanes2011_2012","nhanes2013_2014", "nhanes2015_2016", "nhanes2017_2018"),"mean_frs"=c(16.38,16.62, 15,	14.52	,14.42,	13.92	,13.88,	13.56	,13.79,	13.51	,13.81,	13.87))

df_plot %>% ggplot(aes(x = survey, y = mean_frs)) +
              geom_point() + 
              geom_smooth(method = "lm")

```

