---
title: "NHANESII_III_analysis"
author: "Bryan Kim"
date: "1/13/2021"
output: pdf_document
---
# First get compute FRS functions
```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/compute_frs.R")
```


########################################## 

# TABS

########################################## 
## Old Framingham
### NHANES II

```{r}
library(haven)
library(dplyr)

nhanesII=read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/NHANESII/nhanesII_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0))
nhanesII = nhanesII[complete.cases(nhanesII[ , c("SEX","AGEYR_AT_INT","lbdhdd","lbxtc","asbp","curr_smq","fpg_reg")]),]

nhanesII$frs = mapply(get_frs, nhanesII$SEX,nhanesII$AGEYR_AT_INT,nhanesII$lbdhdd,nhanesII$lbxtc,nhanesII$asbp,nhanesII$curr_smq,nhanesII$fpg_reg)
# ALL
weighted.mean(nhanesII$frs,nhanesII$exam_final_wt)
weighted.mean(nhanesII$frs,nhanesII$wt)


table(nhanesII$GRADE)

#FOR NHANES II
nhanesII = nhanesII %>% filter(GRADE != 88)
tempII = list(nhanesII)
length(tempII) # should be 1
##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$frs,temp$wt))})

# HS
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$frs,temp$wt))})

# Some College
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$frs,temp$wt))})

# College Grad
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$frs,temp$wt))})

# 55-64
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$frs,temp$wt))})

# 65-74
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$frs,temp$wt))})

# 75+
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$frs,temp$wt))})



############################################################
nhanesII$isDiabetic = ifelse(nhanesII$fpg>=126,1,0)
subset=nhanesII %>% filter()
table(nhanesII$fpg,nhanesII$M1)

```

### NHANES III

```{r}
nhanesIIIP1 = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/NHANESIII/nhanesIIIP1_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0))
nhanesIIIP2 = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/NHANESIII/nhanesIIIP2_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0))
nhanesIIIP1 = nhanesIIIP1[complete.cases(nhanesIIIP1[ , c("HSSEX","HSAGEIR","hdl","lbxtc","asbp","curr_smq","fpg_reg")]),]
nhanesIIIP2 = nhanesIIIP2[complete.cases(nhanesIIIP2[ , c("HSSEX","HSAGEIR","hdl","lbxtc","asbp","curr_smq","fpg_reg")]),]

source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES II&III/create_wts_from_cleaned_old_nhanesIII.R")

nhanesIIIP1$frs = mapply(get_frs, nhanesIIIP1$HSSEX,nhanesIIIP1$HSAGEIR,nhanesIIIP1$hdl,nhanesIIIP1$lbxtc,nhanesIIIP1$asbp,nhanesIIIP1$smoke_sts,nhanesIIIP1$fpg_reg)
nhanesIIIP2$frs = mapply(get_frs, nhanesIIIP2$HSSEX,nhanesIIIP2$HSAGEIR,nhanesIIIP2$hdl,nhanesIIIP2$lbxtc,nhanesIIIP2$asbp,nhanesIIIP2$smoke_sts,nhanesIIIP2$fpg_reg)

#FOR NHANES III
tempIII = list(nhanesIIIP1,nhanesIIIP2)
tempIIIP1 = list(nhanesIIIP1)
tempIIIP2 = list(nhanesIIIP2)

length(tempIII) # should be 2

# ALL
weighted.mean(nhanesIIIP1$frs,nhanesIIIP1$WTPFQX1)
weighted.mean(nhanesIIIP1$frs,nhanesIIIP1$wt)
weighted.mean(nhanesIIIP2$frs,nhanesIIIP2$WTPFQX2)
weighted.mean(nhanesIIIP2$frs,nhanesIIIP2$wt)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs,temp$wt))})

# HS
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs,temp$wt))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs,temp$wt))})

# Some College
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs,temp$wt))})

# College Grad
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs,temp$wt))})

# 55-64
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs,temp$wt))})

# 65-74
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs,temp$wt))})

# 75+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$frs,temp$wt))})

# 85+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >= 85);print(weighted.mean(temp$frs,temp$wt))})

############################################################

```

## ATP-3

### NHANESII

```{r}
nhanesII_atp3 = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/ATP3/nhanesII_frs_atp3.dta")
View(nhanesII_atp3 %>% select("SEX","AGEYR_AT_INT","lbdhdd","lbxtc","asbp","curr_smq","treated","frs_atp3"))
table(nhanesII_atp3$AGEYR_AT_INT)

nhanesII_atp3$frs = mapply(get_frs, nhanesII_atp3$SEX,nhanesII_atp3$AGEYR_AT_INT,nhanesII_atp3$lbdhdd,nhanesII_atp3$lbxtc,nhanesII_atp3$asbp,nhanesII_atp3$curr_smq,nhanesII_atp3$fpg_reg)
# ALL
weighted.mean(nhanesII_atp3$frs,nhanesII_atp3$exam_final_wt)
weighted.mean(nhanesII_atp3$frs,nhanesII_atp3$wt)

weighted.mean(nhanesII_atp3$frs_atp3,nhanesII_atp3$exam_final_wt)
weighted.mean(nhanesII_atp3$frs_atp3,nhanesII_atp3$wt)


table(nhanesII_atp3$GRADE)

#FOR NHANES II
nhanesII_atp3 = nhanesII_atp3 %>% filter(GRADE != 88)
tempII = list(nhanesII_atp3)
length(tempII) # should be 1
##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$frs_atp3,temp$wt))})

# HS
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$frs_atp3,temp$wt))})

# Some College
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$frs_atp3,temp$wt))})

# College Grad
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$frs_atp3,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 55-64
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 65-74
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 75+
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$frs_atp3,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$frs_atp3,temp$wt))})



############################################################
nhanesII_atp3$isDiabetic = ifelse(nhanesII_atp3$fpg>=126,1,0)
subset=nhanesII_atp3 %>% filter()
table(nhanesII_atp3$fpg,nhanesII_atp3$M1)

```

### NHANES III

```{r}
nhanesIIIP1_atp3 = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/ATP3/nhanesIII_P1x_frs_atp3.dta") %>% filter(HSAGEIR <= 74)
nhanesIIIP2_atp3 = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/ATP3/nhanesIII_P2x_frs_atp3.dta") %>% filter(HSAGEIR <= 74)

source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES II&III/create_wts_nhanesIII.R")

#FOR NHANES III
tempIII = list(nhanesIIIP1_atp3,nhanesIIIP2_atp3)
tempIIIP1 = list(nhanesIIIP1_atp3)
tempIIIP2 = list(nhanesIIIP2_atp3)

length(tempIII) # should be 2

# ALL
weighted.mean(nhanesIIIP1_atp3$frs_atp3,nhanesIIIP1_atp3$WTPFQX1)
weighted.mean(nhanesIIIP1_atp3$frs_atp3,nhanesIIIP1_atp3$wt)
weighted.mean(nhanesIIIP2_atp3$frs_atp3,nhanesIIIP2_atp3$WTPFQX2)
weighted.mean(nhanesIIIP2_atp3$frs_atp3,nhanesIIIP2_atp3$wt)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$frs_atp3,temp$wt))})

# HS
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs_atp3,temp$wt))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$frs_atp3,temp$wt))})

# Some College
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$frs_atp3,temp$wt))})

# College Grad
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$frs_atp3,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
```

```{r}
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 55-64
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 65-74
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs_atp3,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs_atp3,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 75+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$frs_atp3,temp$wt))})

# 85+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >= 85);print(weighted.mean(temp$frs_atp3,temp$wt))})

############################################################
```

## Pooled Cohort 

### NHANES II
```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/compute_frs_pooled.R")

nhanesII_pooled=read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/nhanesII/nhanesII_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0)) %>% filter(race != 3) 
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES II&III/create_wts_from_cleaned_pooled_nhanesII.R")

nhanesII_pooled = nhanesII_pooled %>% mutate(MW = ifelse(race == 1 & SEX == 1, 1, 0))
nhanesII_pooled = nhanesII_pooled %>% mutate(FW = ifelse(race == 1 & SEX == 2, 1, 0))
nhanesII_pooled = nhanesII_pooled %>% mutate(MB = ifelse(race == 2 & SEX == 1, 1, 0))
nhanesII_pooled = nhanesII_pooled %>% mutate(FB = ifelse(race == 2 & SEX == 2, 1, 0))
# coalesce into one variable `race_sex_cat`
nhanesII_pooled$race_sex_cat = ifelse(nhanesII_pooled$MW==1, 1, NA)
nhanesII_pooled$race_sex_cat[nhanesII_pooled$FW == 1] = 2
nhanesII_pooled$race_sex_cat[nhanesII_pooled$MB == 1] = 3
nhanesII_pooled$race_sex_cat[nhanesII_pooled$FB == 1] = 4

nhanesIIIP1_pooled = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/NHANESIII/nhanesIIIP1_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0)) %>% filter(race != 3) 
nhanesIIIP2_pooled = read_dta("/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/NHANESIII/nhanesIIIP2_frs_old.dta") %>% mutate(isDiabetic = ifelse(fpg_reg >= 126,1,0)) %>% filter(race != 3) 

source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES II&III/create_wts_from_cleaned_pooled_nhanesIII.R")

nhanesIIIP1_pooled = nhanesIIIP1_pooled[complete.cases(nhanesIIIP1_pooled[ , c("HSSEX","HSAGEIR","hdl","lbxtc","asbp","curr_smq","fpg_reg")]),]
nhanesIIIP2_pooled = nhanesIIIP2_pooled[complete.cases(nhanesIIIP2_pooled[ , c("HSSEX","HSAGEIR","hdl","lbxtc","asbp","curr_smq","fpg_reg")]),]
nhanesIIIP1_pooled = nhanesIIIP1_pooled %>% mutate(MW = ifelse(race == 1 & HSSEX == 1, 1, 0))
nhanesIIIP1_pooled = nhanesIIIP1_pooled %>% mutate(FW = ifelse(race == 1 & HSSEX == 2, 1, 0))
nhanesIIIP1_pooled = nhanesIIIP1_pooled %>% mutate(MB = ifelse(race == 2 & HSSEX == 1, 1, 0))
nhanesIIIP1_pooled = nhanesIIIP1_pooled %>% mutate(FB = ifelse(race == 2 & HSSEX == 2, 1, 0))
# coalesce into one variable `race_sex_cat`
nhanesIIIP1_pooled$race_sex_cat = ifelse(nhanesIIIP1_pooled$MW==1, 1, NA)
nhanesIIIP1_pooled$race_sex_cat[nhanesIIIP1_pooled$FW == 1] = 2
nhanesIIIP1_pooled$race_sex_cat[nhanesIIIP1_pooled$MB == 1] = 3
nhanesIIIP1_pooled$race_sex_cat[nhanesIIIP1_pooled$FB == 1] = 4
nhanesIIIP2_pooled = nhanesIIIP2_pooled %>% mutate(MW = ifelse(race == 1 & HSSEX == 1, 1, 0))
nhanesIIIP2_pooled = nhanesIIIP2_pooled %>% mutate(FW = ifelse(race == 1 & HSSEX == 2, 1, 0))
nhanesIIIP2_pooled = nhanesIIIP2_pooled %>% mutate(MB = ifelse(race == 2 & HSSEX == 1, 1, 0))
nhanesIIIP2_pooled = nhanesIIIP2_pooled %>% mutate(FB = ifelse(race == 2 & HSSEX == 2, 1, 0))
# coalesce into one variable `race_sex_cat`
nhanesIIIP2_pooled$race_sex_cat = ifelse(nhanesIIIP2_pooled$MW==1, 1, NA)
nhanesIIIP2_pooled$race_sex_cat[nhanesIIIP2_pooled$FW == 1] = 2
nhanesIIIP2_pooled$race_sex_cat[nhanesIIIP2_pooled$MB == 1] = 3
nhanesIIIP2_pooled$race_sex_cat[nhanesIIIP2_pooled$FB == 1] = 4


# Race-Sex specific means
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES II&III/get_racesex_means.R")


nhanesII_pooled$pooled_frs = get_pooled_frs %>% mapply("nhanesII_pooled",nhanesII_pooled$race,nhanesII_pooled$SEX,nhanesII_pooled$AGEYR_AT_INT,nhanesII_pooled$lbdhdd,nhanesII_pooled$lbxtc,nhanesII_pooled$asbp,nhanesII_pooled$curr_smq,nhanesII_pooled$isDiabetic)
nhanesII_pooled$pooled_frs = as.numeric(unlist(nhanesII_pooled$pooled_frs))

tempII = list(nhanesII_pooled)
length(tempII) # should be 1

# ALL
weighted.mean(nhanesII_pooled$pooled_frs,nhanesII_pooled$exam_final_wt)
weighted.mean(nhanesII_pooled$pooled_frs,nhanesII_pooled$wt)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE < 34);print(weighted.mean(temp$pooled_frs,temp$wt))})

# HS
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 34 & x$GRADE_COMPL == 1);print(weighted.mean(temp$pooled_frs,temp$wt))})

# Some College
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE > 34 & x$GRADE < 45);print(weighted.mean(temp$pooled_frs,temp$wt))})

# College Grad
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$GRADE == 45);print(weighted.mean(temp$pooled_frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=45 & x$AGEYR_AT_INT <=54);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 55-64
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=55 & x$AGEYR_AT_INT <=64);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 65-74
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=65 & x$AGEYR_AT_INT <=74);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 75+
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$pooled_frs,temp$exam_final_wt))})
lapply(tempII, function(x) {temp = filter(x,x$AGEYR_AT_INT >=75);print(weighted.mean(temp$pooled_frs,temp$wt))})


```


### NHANES III
```{r}
nhanesIIIP1_pooled$pooled_frs = get_pooled_frs %>% mapply("nhanesIIIP1_pooled",nhanesIIIP1_pooled$race,nhanesIIIP1_pooled$HSSEX,nhanesIIIP1_pooled$HSAGEIR,nhanesIIIP1_pooled$hdl,nhanesIIIP1_pooled$lbxtc,nhanesIIIP1_pooled$asbp,nhanesIIIP1_pooled$curr_smq,nhanesIIIP1_pooled$isDiabetic)
nhanesIIIP1_pooled$pooled_frs = as.numeric(unlist(nhanesIIIP1_pooled$pooled_frs))
nhanesIIIP2_pooled$pooled_frs = get_pooled_frs %>% mapply("nhanesIIIP2_pooled",nhanesIIIP2_pooled$race,nhanesIIIP2_pooled$HSSEX,nhanesIIIP2_pooled$HSAGEIR,nhanesIIIP2_pooled$hdl,nhanesIIIP2_pooled$lbxtc,nhanesIIIP2_pooled$asbp,nhanesIIIP2_pooled$curr_smq,nhanesIIIP2_pooled$isDiabetic)
nhanesIIIP2_pooled$pooled_frs = as.numeric(unlist(nhanesIIIP2_pooled$pooled_frs))

#FOR NHANES III
tempIII = list(nhanesIIIP1_pooled,nhanesIIIP2_pooled)
tempIIIP1 = list(nhanesIIIP1_pooled)
tempIIIP2 = list(nhanesIIIP2_pooled)

length(tempIII) # should be 2

# ALL
weighted.mean(nhanesIIIP1_pooled$pooled_frs,nhanesIIIP1_pooled$WTPFQX1)
weighted.mean(nhanesIIIP1_pooled$pooled_frs,nhanesIIIP1_pooled$wt)
weighted.mean(nhanesIIIP2_pooled$pooled_frs,nhanesIIIP2_pooled$WTPFQX2)
weighted.mean(nhanesIIIP2_pooled$pooled_frs,nhanesIIIP2_pooled$wt)

##### BY EDUCATION #####
# <HS 
# <HS 
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R <= 11);print(weighted.mean(temp$pooled_frs,temp$wt))})

# HS
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$pooled_frs,temp$wt))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R == 12);print(weighted.mean(temp$pooled_frs,temp$wt))})

# Some College
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R > 12 & x$HFA8R < 16);print(weighted.mean(temp$pooled_frs,temp$wt))})

# College Grad
lapply(tempIIIP1, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HFA8R >= 16);print(weighted.mean(temp$pooled_frs,temp$wt))})

##### BY AGE #####
# 45-54
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=45 & x$HSAGEIR <=54);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 55-64
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=55 & x$HSAGEIR <=64);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 65-74
lapply(tempIIIP1, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$pooled_frs,temp$WTPFQX1))})
lapply(tempIIIP2, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$pooled_frs,temp$WTPFQX2))})
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=65 & x$HSAGEIR <=74);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 75+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >=75);print(weighted.mean(temp$pooled_frs,temp$wt))})

# 85+
lapply(tempIII, function(x) {temp = filter(x,x$HSAGEIR >= 85);print(weighted.mean(temp$pooled_frs,temp$wt))})
```
