---
title: "Untitled"
author: "Bryan Kim"
date: "1/27/2021"
output: pdf_document
---


# get data with adjusted weights

```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/load_data.R")

nhanes1999_2000= nhanes1999_2000 %>% filter((race %in% c(1,2)))
nhanes2001_2002= nhanes2001_2002 %>% filter((race %in% c(1,2)))
nhanes2003_2004= nhanes2003_2004 %>% filter((race %in% c(1,2)))
nhanes2005_2006= nhanes2005_2006 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2007_2008= nhanes2007_2008 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2009_2010= nhanes2009_2010 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2011_2012= nhanes2011_2012 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2013_2014= nhanes2013_2014 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2015_2016= nhanes2015_2016 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))
nhanes2017_2018= nhanes2017_2018 %>% filter((race %in% c(3,4))) %>% mutate(race=ifelse(race==3,1,2))

df_list_pooled = list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

print(length(df_list_pooled))
```

# return functions for computing frs

```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/compute_frs.R")

source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/create_race_sex_dummies.R")

nhanes1999_2000$frs_pooled = mapply(get_pooled_frs,"nhanes1999_2000",nhanes1999_2000$race, nhanes1999_2000$riagendr,nhanes1999_2000$ridageyr,nhanes1999_2000$hdl,nhanes1999_2000$lbxtc,nhanes1999_2000$asbp,nhanes1999_2000$curr_smq,nhanes1999_2000$isDiabetic);nhanes1999_2000$frs_pooled = as.numeric(unlist(nhanes1999_2000$frs_pooled))
nhanes2001_2002$frs_pooled = mapply(get_pooled_frs,"nhanes2001_2002",nhanes2001_2002$race, nhanes2001_2002$riagendr,nhanes2001_2002$ridageyr,nhanes2001_2002$hdl,nhanes2001_2002$lbxtc,nhanes2001_2002$asbp,nhanes2001_2002$curr_smq,nhanes2001_2002$isDiabetic);nhanes2001_2002$frs_pooled = as.numeric(unlist(nhanes2001_2002$frs_pooled))
nhanes2003_2004$frs_pooled = mapply(get_pooled_frs,"nhanes2003_2004",nhanes2003_2004$race, nhanes2003_2004$riagendr,nhanes2003_2004$ridageyr,nhanes2003_2004$hdl,nhanes2003_2004$lbxtc,nhanes2003_2004$asbp,nhanes2003_2004$curr_smq,nhanes2003_2004$isDiabetic);nhanes2003_2004$frs_pooled = as.numeric(unlist(nhanes2003_2004$frs_pooled))
nhanes2005_2006$frs_pooled = mapply(get_pooled_frs,"nhanes2005_2006",nhanes2005_2006$race, nhanes2005_2006$riagendr,nhanes2005_2006$ridageyr,nhanes2005_2006$hdl,nhanes2005_2006$lbxtc,nhanes2005_2006$asbp,nhanes2005_2006$curr_smq,nhanes2005_2006$isDiabetic);nhanes2005_2006$frs_pooled = as.numeric(unlist(nhanes2005_2006$frs_pooled))
nhanes2007_2008$frs_pooled = mapply(get_pooled_frs,"nhanes2007_2008",nhanes2007_2008$race, nhanes2007_2008$riagendr,nhanes2007_2008$ridageyr,nhanes2007_2008$hdl,nhanes2007_2008$lbxtc,nhanes2007_2008$asbp,nhanes2007_2008$curr_smq,nhanes2007_2008$isDiabetic);nhanes2007_2008$frs_pooled = as.numeric(unlist(nhanes2007_2008$frs_pooled))
nhanes2009_2010$frs_pooled = mapply(get_pooled_frs,"nhanes2009_2010",nhanes2009_2010$race, nhanes2009_2010$riagendr,nhanes2009_2010$ridageyr,nhanes2009_2010$hdl,nhanes2009_2010$lbxtc,nhanes2009_2010$asbp,nhanes2009_2010$curr_smq,nhanes2009_2010$isDiabetic);nhanes2009_2010$frs_pooled = as.numeric(unlist(nhanes2009_2010$frs_pooled))
nhanes2011_2012$frs_pooled = mapply(get_pooled_frs,"nhanes2011_2012",nhanes2011_2012$race, nhanes2011_2012$riagendr,nhanes2011_2012$ridageyr,nhanes2011_2012$hdl,nhanes2011_2012$lbxtc,nhanes2011_2012$asbp,nhanes2011_2012$curr_smq,nhanes2011_2012$isDiabetic);nhanes2011_2012$frs_pooled = as.numeric(unlist(nhanes2011_2012$frs_pooled))
nhanes2013_2014$frs_pooled = mapply(get_pooled_frs,"nhanes2013_2014",nhanes2013_2014$race, nhanes2013_2014$riagendr,nhanes2013_2014$ridageyr,nhanes2013_2014$hdl,nhanes2013_2014$lbxtc,nhanes2013_2014$asbp,nhanes2013_2014$curr_smq,nhanes2013_2014$isDiabetic);nhanes2013_2014$frs_pooled = as.numeric(unlist(nhanes2013_2014$frs_pooled))
nhanes2015_2016$frs_pooled = mapply(get_pooled_frs,"nhanes2015_2016",nhanes2015_2016$race, nhanes2015_2016$riagendr,nhanes2015_2016$ridageyr,nhanes2015_2016$hdl,nhanes2015_2016$lbxtc,nhanes2015_2016$asbp,nhanes2015_2016$curr_smq,nhanes2015_2016$isDiabetic);nhanes2015_2016$frs_pooled = as.numeric(unlist(nhanes2015_2016$frs_pooled))
nhanes2017_2018$frs_pooled = mapply(get_pooled_frs,"nhanes2017_2018",nhanes2017_2018$race, nhanes2017_2018$riagendr,nhanes2017_2018$ridageyr,nhanes2017_2018$hdl,nhanes2017_2018$lbxtc,nhanes2017_2018$asbp,nhanes2017_2018$curr_smq,nhanes2017_2018$isDiabetic);nhanes2017_2018$frs_pooled = as.numeric(unlist(nhanes2017_2018$frs_pooled))

df_list_pooled = list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

```


### get scores
```{r}
"ALL"
lapply(df_list_pooled, function(x) print(weighted.mean(x$frs_pooled,x$wtint2yr)))
lapply(df_list_pooled, function(x) print(weighted.mean(x$frs_pooled,x$wt)))

##### BY EDUCATION #####
# <HS 
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 <= 2);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})

# HS
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 3);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})

# Some College
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 4);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})

# College Grad
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 5);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})

##### BY AGE #####
# 45-54
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=45 & x$ridageyr <=54);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})
# 55-64
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=55 & x$ridageyr <=64);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})
# 65-74
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=65 & x$ridageyr <=74);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})
# 75+
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=75);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})
# 85+
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >= 85);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wtint2yr))})

## AGE-SEX ADJUSTED ##
##### BY EDUCATION #####
# <HS 
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 <= 2);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})

# HS
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 3);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})

# Some College
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 4);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})

# College Grad
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$dmdeduc2 == 5);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})

##### BY AGE #####
# 45-54
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=45 & x$ridageyr <=54);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})
# 55-64
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=55 & x$ridageyr <=64);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})
# 65-74
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=65 & x$ridageyr <=74);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})
# 75+
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >=75);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})
# 85+
lapply(df_list_pooled, function(x) {df_list_pooled = filter(x,x$ridageyr >= 85);print(weighted.mean(df_list_pooled$frs_pooled,df_list_pooled$wt))})


```




