---
title: "get_frs"
author: "Bryan Kim"
date: "1/21/2021"
output: pdf_document
---

# get data with adjusted weights

```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/load_data_old.R")

df_list = list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

print(length(df_list))
```

# return functions for computing frs

```{r}
source("/Users/bryankim/Documents/NBER/Case Deaton/Code/NHANES_continuous/compute_frs.R")

nhanes1999_2000$frs = mapply(get_frs, nhanes1999_2000$sex,nhanes1999_2000$age,nhanes1999_2000$hdl,nhanes1999_2000$lbxtc,nhanes1999_2000$asbp,nhanes1999_2000$smq020,nhanes1999_2000$lbxgh)
nhanes2001_2002$frs = mapply(get_frs, nhanes2001_2002$sex,nhanes2001_2002$age,nhanes2001_2002$hdl,nhanes2001_2002$lbxtc,nhanes2001_2002$asbp,nhanes2001_2002$curr_smq,nhanes2001_2002$lbxgh)
nhanes2003_2004$frs = mapply(get_frs, nhanes2003_2004$sex,nhanes2003_2004$age,nhanes2003_2004$hdl,nhanes2003_2004$lbxtc,nhanes2003_2004$asbp,nhanes2003_2004$curr_smq,nhanes2003_2004$lbxgh)
nhanes2005_2006$frs = mapply(get_frs, nhanes2005_2006$sex,nhanes2005_2006$age,nhanes2005_2006$hdl,nhanes2005_2006$lbxtc,nhanes2005_2006$asbp,nhanes2005_2006$curr_smq,nhanes2005_2006$lbxgh)
nhanes2007_2008$frs = mapply(get_frs, nhanes2007_2008$sex,nhanes2007_2008$age,nhanes2007_2008$hdl,nhanes2007_2008$lbxtc,nhanes2007_2008$asbp,nhanes2007_2008$curr_smq,nhanes2007_2008$lbxgh)
nhanes2009_2010$frs = mapply(get_frs, nhanes2009_2010$sex,nhanes2009_2010$age,nhanes2009_2010$hdl,nhanes2009_2010$lbxtc,nhanes2009_2010$asbp,nhanes2009_2010$curr_smq,nhanes2009_2010$lbxgh)
nhanes2011_2012$frs = mapply(get_frs, nhanes2011_2012$sex,nhanes2011_2012$age,nhanes2011_2012$hdl,nhanes2011_2012$lbxtc,nhanes2011_2012$asbp,nhanes2011_2012$curr_smq,nhanes2011_2012$lbxgh)
nhanes2013_2014$frs = mapply(get_frs, nhanes2013_2014$sex,nhanes2013_2014$age,nhanes2013_2014$hdl,nhanes2013_2014$lbxtc,nhanes2013_2014$asbp,nhanes2013_2014$curr_smq,nhanes2013_2014$lbxgh)
nhanes2015_2016$frs = mapply(get_frs, nhanes2015_2016$sex,nhanes2015_2016$age,nhanes2015_2016$hdl,nhanes2015_2016$lbxtc,nhanes2015_2016$asbp,nhanes2015_2016$curr_smq,nhanes2015_2016$lbxgh)
nhanes2017_2018$frs = mapply(get_frs, nhanes2017_2018$sex,nhanes2017_2018$age,nhanes2017_2018$hdl,nhanes2017_2018$lbxtc,nhanes2017_2018$asbp,nhanes2017_2018$curr_smq,nhanes2017_2018$lbxgh)

df_list = list(nhanes1999_2000,nhanes2001_2002,nhanes2003_2004,nhanes2005_2006,nhanes2007_2008,nhanes2009_2010,nhanes2011_2012,nhanes2013_2014,nhanes2015_2016,nhanes2017_2018)

```


### get scores
```{r}
"ALL"
lapply(df_list, function(x) print(weighted.mean(x$frs,x$wtint2yr)))
lapply(df_list, function(x) print(weighted.mean(x$frs,x$wgt)))

##### BY EDUCATION #####
# <HS 
lapply(df_list, function(x) {df_list = filter(x,x$grade <= 2);print(weighted.mean(df_list$frs,df_list$wtint2yr))})

# HS
lapply(df_list, function(x) {df_list = filter(x,x$grade == 3);print(weighted.mean(df_list$frs,df_list$wtint2yr))})

# Some College
lapply(df_list, function(x) {df_list = filter(x,x$grade == 4);print(weighted.mean(df_list$frs,df_list$wtint2yr))})

# College Grad
lapply(df_list, function(x) {df_list = filter(x,x$grade == 5);print(weighted.mean(df_list$frs,df_list$wtint2yr))})

##### BY AGE #####
# 45-54
lapply(df_list, function(x) {df_list = filter(x,x$age >=45 & x$age <=54);print(weighted.mean(df_list$frs,df_list$wtint2yr))})
# 55-64
lapply(df_list, function(x) {df_list = filter(x,x$age >=55 & x$age <=64);print(weighted.mean(df_list$frs,df_list$wtint2yr))})
# 65-74
lapply(df_list, function(x) {df_list = filter(x,x$age >=65 & x$age <=74);print(weighted.mean(df_list$frs,df_list$wtint2yr))})
# # 75+
# lapply(df_list, function(x) {df_list = filter(x,x$age >=75);print(weighted.mean(df_list$frs,df_list$wtint2yr))})
# # 85+
# lapply(df_list, function(x) {df_list = filter(x,x$age >= 85);print(weighted.mean(df_list$frs,df_list$wtint2yr))})

## AGE-SEX ADJUSTED ##
##### BY EDUCATION #####
# <HS 
lapply(df_list, function(x) {df_list = filter(x,x$grade <= 2);print(weighted.mean(df_list$frs,df_list$wgt))})

# HS
lapply(df_list, function(x) {df_list = filter(x,x$grade == 3);print(weighted.mean(df_list$frs,df_list$wgt))})

# Some College
lapply(df_list, function(x) {df_list = filter(x,x$grade == 4);print(weighted.mean(df_list$frs,df_list$wgt))})

# College Grad
lapply(df_list, function(x) {df_list = filter(x,x$grade == 5);print(weighted.mean(df_list$frs,df_list$wgt))})

##### BY AGE #####
# 45-54
lapply(df_list, function(x) {df_list = filter(x,x$age >=45 & x$age <=54);print(weighted.mean(df_list$frs,df_list$wgt))})
# 55-64
lapply(df_list, function(x) {df_list = filter(x,x$age >=55 & x$age <=64);print(weighted.mean(df_list$frs,df_list$wgt))})
# 65-74
lapply(df_list, function(x) {df_list = filter(x,x$age >=65 & x$age <=74);print(weighted.mean(df_list$frs,df_list$wgt))})
# # 75+
# lapply(df_list, function(x) {df_list = filter(x,x$age >=75);print(weighted.mean(df_list$frs,df_list$wgt))})
# # 85+
# lapply(df_list, function(x) {df_list = filter(x,x$age >= 85);print(weighted.mean(df_list$frs,df_list$wgt))})


```
```{r}
write_dta(nhanes1999_2000,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_1999_2000_frs_old.dta") 
write_dta(nhanes2001_2002,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2001_2002_frs_old.dta") 
write_dta(nhanes2003_2004,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2003_2004_frs_old.dta") 
write_dta(nhanes2005_2006,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2005_2006_frs_old.dta") 
write_dta(nhanes2007_2008,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2007_2008_frs_old.dta") 
write_dta(nhanes2009_2010,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2009_2010_frs_old.dta") 
write_dta(nhanes2011_2012,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2011_2012_frs_old.dta") 
write_dta(nhanes2013_2014,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2013_2014_frs_old.dta") 
write_dta(nhanes2015_2016,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2015_2016_frs_old.dta") 
write_dta(nhanes2017_2018,"/Users/bryankim/Documents/NBER/Case Deaton/Data/FRS/Old Framingham/continuous/nhanes_2017_2018_frs_old.dta") 

```




